import type { ComponentType } from "react";
import type { SymbolDefinition, SymbolRenderProps } from "../../types/scadaMimic";
import {
  BreakerSymbol,
  BusbarHorizontalSymbol,
  BusbarVerticalSymbol,
  DisconnectorSymbol,
  GenBlockSymbol,
  LineFeederSymbol,
  LoadBlockSymbol,
  MeterSymbol,
  TransformerTwoWindingSymbol,
} from "./electrical";
import {
  DataBlockSymbol,
  EllipseSymbol,
  LabelSymbol,
  PipeJunctionSymbol,
  PipeSegmentSymbol,
  PipeTeeSymbol,
  PipelineTrackSymbol,
  PumpCentrifugalSymbol,
  PumpPositiveSymbol,
  RectSymbol,
  SensorGaugeInlineSymbol,
  SensorIndicatorSymbol,
  StatusArrowSymbol,
  TableEmbeddedSymbol,
  TankHorizontalSymbol,
  TankVerticalSymbol,
  ValveButterflySymbol,
  ValveCheckSymbol,
  ValveGateSymbol,
  ValueBadgeSymbol,
} from "./process";
import {
  AlarmBannerSymbol,
  ArrowSymbol,
  CapacitorSymbol,
  CompressorSymbol,
  ContactSymbol,
  DiamondSymbol,
  FilterSymbol,
  FlareSymbol,
  FuseSymbol,
  GroundSymbol,
  HeatExchangerSymbol,
  InverterSymbol,
  MixerSymbol,
  MotorSymbol,
  PumpSubmersibleSymbol,
  ReactorSymbol,
  SeparatorSymbol,
  SensorPressureSymbol,
  SensorTemperatureSymbol,
  TankSphericalSymbol,
  TextMultilineSymbol,
  TransformerThreeWindingSymbol,
  ValveBallSymbol,
  ValveGlobeSymbol,
} from "./extra";
import {
  AgitatorSymbol,
  AmmeterSymbol,
  ArresterSymbol,
  BatterySymbol,
  BlindFlangeSymbol,
  BoilerSymbol,
  CalloutSymbol,
  ColumnDistillationSymbol,
  ConnectorSymbol,
  ConveyorSymbol,
  CurrentTransformerSymbol,
  DamperSymbol,
  EarthingSwitchSymbol,
  FanBlowerSymbol,
  FrameSymbol,
  FurnaceSymbol,
  HopperSymbol,
  LegendBoxSymbol,
  LevelGaugeSymbol,
  LineHorizontalSymbol,
  LineVerticalSymbol,
  ManualSwitchSymbol,
  MotorStarterSymbol,
  OrificeSymbol,
  PipeElbowSymbol,
  PipeReducerSymbol,
  PilotLampSymbol,
  PlcSymbol,
  PotentialTransformerSymbol,
  ReactorVesselSymbol,
  RelaySymbol,
  SiloSymbol,
  SolarPanelSymbol,
  SteamTrapSymbol,
  SteamTurbineSymbol,
  TankConicalSymbol,
  UpsSymbol,
  ValveControlSymbol,
  ValveDiaphragmSymbol,
  ValveNeedleSymbol,
  ValveSafetySymbol,
  VentSymbol,
  VoltmeterSymbol,
  WindTurbineSymbol,
} from "./industrial";
import { DOMAIN_CATEGORY_IDS, DOMAIN_SYMBOLS } from "./domainCatalog";

export interface RegisteredSymbol extends SymbolDefinition {
  render: ComponentType<SymbolRenderProps>;
  paletteProps?: Record<string, unknown>;
}

const port = (id: string, x: number, y: number) => ({ id, x, y });

const SYMBOLS: RegisteredSymbol[] = [
  {
    id: "tank.vertical",
    category: "process",
    nameKey: "symbols.tankVertical",
    defaultWidth: 80,
    defaultHeight: 120,
    ports: [port("n", 40, 0), port("s", 40, 120), port("e", 80, 60), port("w", 0, 60)],
    bindingSchema: [
      { key: "fillLevel", labelKey: "bindings.fillLevel", type: "number" },
      { key: "maxLevel", labelKey: "bindings.maxLevel", type: "number", optional: true },
      { key: "rate", labelKey: "bindings.rate", type: "number", optional: true },
    ],
    render: TankVerticalSymbol,
  },
  {
    id: "tank.horizontal",
    category: "process",
    nameKey: "symbols.tankHorizontal",
    defaultWidth: 120,
    defaultHeight: 80,
    ports: [port("n", 60, 0), port("s", 60, 80), port("e", 120, 40), port("w", 0, 40)],
    bindingSchema: [
      { key: "fillLevel", labelKey: "bindings.fillLevel", type: "number" },
      { key: "maxLevel", labelKey: "bindings.maxLevel", type: "number", optional: true },
    ],
    render: TankHorizontalSymbol,
  },
  {
    id: "valve.butterfly",
    category: "process",
    nameKey: "symbols.valveButterfly",
    defaultWidth: 40,
    defaultHeight: 60,
    ports: [port("n", 20, 0), port("s", 20, 60)],
    bindingSchema: [
      { key: "open", labelKey: "bindings.open", type: "boolean" },
      { key: "intermediate", labelKey: "bindings.intermediate", type: "boolean", optional: true },
    ],
    render: ValveButterflySymbol,
  },
  {
    id: "valve.gate",
    category: "process",
    nameKey: "symbols.valveGate",
    defaultWidth: 36,
    defaultHeight: 56,
    ports: [port("n", 18, 0), port("s", 18, 56)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveGateSymbol,
  },
  {
    id: "valve.check",
    category: "process",
    nameKey: "symbols.valveCheck",
    defaultWidth: 36,
    defaultHeight: 36,
    ports: [port("w", 0, 18), port("e", 36, 18)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveCheckSymbol,
  },
  {
    id: "pump.centrifugal",
    category: "process",
    nameKey: "symbols.pumpCentrifugal",
    defaultWidth: 56,
    defaultHeight: 56,
    ports: [port("n", 28, 0), port("s", 28, 56), port("e", 56, 28), port("w", 0, 28)],
    bindingSchema: [
      { key: "running", labelKey: "bindings.running", type: "boolean" },
      { key: "fault", labelKey: "bindings.fault", type: "boolean", optional: true },
    ],
    render: PumpCentrifugalSymbol,
  },
  {
    id: "pump.positive",
    category: "process",
    nameKey: "symbols.pumpPositive",
    defaultWidth: 56,
    defaultHeight: 56,
    ports: [port("n", 28, 0), port("s", 28, 56)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: PumpPositiveSymbol,
  },
  {
    id: "pipe.segment",
    category: "process",
    nameKey: "symbols.pipeSegment",
    defaultWidth: 80,
    defaultHeight: 16,
    ports: [port("w", 0, 8), port("e", 80, 8)],
    bindingSchema: [{ key: "flowing", labelKey: "bindings.flowing", type: "boolean", optional: true }],
    render: PipeSegmentSymbol,
  },
  {
    id: "pipe.junction",
    category: "process",
    nameKey: "symbols.pipeJunction",
    defaultWidth: 32,
    defaultHeight: 32,
    ports: [port("n", 16, 0), port("s", 16, 32), port("e", 32, 16), port("w", 0, 16)],
    bindingSchema: [],
    render: PipeJunctionSymbol,
  },
  {
    id: "pipe.tee",
    category: "process",
    nameKey: "symbols.pipeTee",
    defaultWidth: 32,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 32, 16), port("s", 16, 32)],
    bindingSchema: [],
    render: PipeTeeSymbol,
  },
  {
    id: "sensor.indicator",
    category: "process",
    nameKey: "symbols.sensorIndicator",
    defaultWidth: 24,
    defaultHeight: 24,
    ports: [],
    bindingSchema: [{ key: "state", labelKey: "bindings.state", type: "enum" }],
    render: SensorIndicatorSymbol,
  },
  {
    id: "sensor.gauge-inline",
    category: "process",
    nameKey: "symbols.sensorGaugeInline",
    defaultWidth: 64,
    defaultHeight: 28,
    ports: [],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: SensorGaugeInlineSymbol,
  },
  {
    id: "data-block",
    category: "process",
    nameKey: "symbols.dataBlock",
    defaultWidth: 100,
    defaultHeight: 64,
    ports: [],
    bindingSchema: [
      { key: "line1", labelKey: "bindings.line1", type: "string", optional: true },
      { key: "line2", labelKey: "bindings.line2", type: "string", optional: true },
      { key: "line3", labelKey: "bindings.line3", type: "string", optional: true },
      { key: "line4", labelKey: "bindings.line4", type: "string", optional: true },
    ],
    render: DataBlockSymbol,
  },
  {
    id: "pipeline-track",
    category: "process",
    nameKey: "symbols.pipelineTrack",
    defaultWidth: 400,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 400, 16)],
    bindingSchema: [],
    render: PipelineTrackSymbol,
  },
  {
    id: "label",
    category: "common",
    nameKey: "symbols.label",
    defaultWidth: 120,
    defaultHeight: 24,
    ports: [],
    bindingSchema: [{ key: "text", labelKey: "bindings.text", type: "string", optional: true }],
    render: LabelSymbol,
  },
  {
    id: "value-badge",
    category: "common",
    nameKey: "symbols.valueBadge",
    defaultWidth: 72,
    defaultHeight: 28,
    ports: [],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: ValueBadgeSymbol,
  },
  {
    id: "status-arrow",
    category: "common",
    nameKey: "symbols.statusArrow",
    defaultWidth: 20,
    defaultHeight: 24,
    ports: [],
    bindingSchema: [{ key: "up", labelKey: "bindings.up", type: "boolean" }],
    render: StatusArrowSymbol,
  },
  {
    id: "rect",
    category: "common",
    nameKey: "symbols.rect",
    defaultWidth: 80,
    defaultHeight: 48,
    ports: [],
    bindingSchema: [],
    render: RectSymbol,
  },
  {
    id: "ellipse",
    category: "common",
    nameKey: "symbols.ellipse",
    defaultWidth: 64,
    defaultHeight: 64,
    ports: [],
    bindingSchema: [],
    render: EllipseSymbol,
  },
  {
    id: "table.embedded",
    category: "common",
    nameKey: "symbols.tableEmbedded",
    defaultWidth: 160,
    defaultHeight: 120,
    ports: [],
    bindingSchema: [],
    render: TableEmbeddedSymbol,
  },
  {
    id: "gen.block",
    category: "electrical",
    nameKey: "symbols.genBlock",
    defaultWidth: 112,
    defaultHeight: 112,
    ports: [port("s", 56, 112)],
    bindingSchema: [
      { key: "running", labelKey: "bindings.running", type: "boolean" },
      { key: "power", labelKey: "bindings.power", type: "number" },
    ],
    render: GenBlockSymbol,
  },
  {
    id: "breaker",
    category: "electrical",
    nameKey: "symbols.breaker",
    defaultWidth: 24,
    defaultHeight: 52,
    ports: [port("n", 12, 0), port("s", 12, 52)],
    bindingSchema: [{ key: "closed", labelKey: "bindings.closed", type: "boolean" }],
    render: BreakerSymbol,
  },
  {
    id: "disconnector",
    category: "electrical",
    nameKey: "symbols.disconnector",
    defaultWidth: 24,
    defaultHeight: 52,
    ports: [port("n", 12, 0), port("s", 12, 52)],
    bindingSchema: [{ key: "closed", labelKey: "bindings.closed", type: "boolean" }],
    render: DisconnectorSymbol,
  },
  {
    id: "busbar.horizontal",
    category: "electrical",
    nameKey: "symbols.busbarHorizontal",
    defaultWidth: 200,
    defaultHeight: 12,
    ports: [port("w", 0, 6), port("e", 200, 6)],
    bindingSchema: [{ key: "energized", labelKey: "bindings.energized", type: "boolean", optional: true }],
    render: BusbarHorizontalSymbol,
  },
  {
    id: "busbar.vertical",
    category: "electrical",
    nameKey: "symbols.busbarVertical",
    defaultWidth: 12,
    defaultHeight: 200,
    ports: [port("n", 6, 0), port("s", 6, 200)],
    bindingSchema: [{ key: "energized", labelKey: "bindings.energized", type: "boolean", optional: true }],
    render: BusbarVerticalSymbol,
  },
  {
    id: "transformer.two-winding",
    category: "electrical",
    nameKey: "symbols.transformerTwoWinding",
    defaultWidth: 56,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 56, 20)],
    bindingSchema: [{ key: "loaded", labelKey: "bindings.loaded", type: "boolean", optional: true }],
    render: TransformerTwoWindingSymbol,
  },
  {
    id: "load.block",
    category: "electrical",
    nameKey: "symbols.loadBlock",
    defaultWidth: 96,
    defaultHeight: 56,
    ports: [port("n", 48, 0)],
    bindingSchema: [{ key: "power", labelKey: "bindings.power", type: "number" }],
    render: LoadBlockSymbol,
  },
  {
    id: "meter",
    category: "electrical",
    nameKey: "symbols.meter",
    defaultWidth: 40,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 40, 20)],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: MeterSymbol,
  },
  {
    id: "line.feeder",
    category: "electrical",
    nameKey: "symbols.lineFeeder",
    defaultWidth: 120,
    defaultHeight: 24,
    ports: [port("w", 0, 12), port("e", 120, 12)],
    bindingSchema: [
      { key: "flowing", labelKey: "bindings.flowing", type: "boolean", optional: true },
      { key: "power", labelKey: "bindings.power", type: "number", optional: true },
    ],
    render: LineFeederSymbol,
  },
  {
    id: "tank.spherical",
    category: "process",
    nameKey: "symbols.tankSpherical",
    defaultWidth: 64,
    defaultHeight: 64,
    ports: [port("s", 32, 64), port("n", 32, 0)],
    bindingSchema: [{ key: "fillLevel", labelKey: "bindings.fillLevel", type: "number" }],
    render: TankSphericalSymbol,
  },
  {
    id: "valve.ball",
    category: "process",
    nameKey: "symbols.valveBall",
    defaultWidth: 40,
    defaultHeight: 60,
    ports: [port("n", 20, 0), port("s", 20, 60)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveBallSymbol,
  },
  {
    id: "valve.globe",
    category: "process",
    nameKey: "symbols.valveGlobe",
    defaultWidth: 36,
    defaultHeight: 56,
    ports: [port("n", 18, 0), port("s", 18, 56)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveGlobeSymbol,
  },
  {
    id: "pump.submersible",
    category: "process",
    nameKey: "symbols.pumpSubmersible",
    defaultWidth: 48,
    defaultHeight: 48,
    ports: [port("n", 24, 0)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: PumpSubmersibleSymbol,
  },
  {
    id: "compressor",
    category: "process",
    nameKey: "symbols.compressor",
    defaultWidth: 64,
    defaultHeight: 48,
    ports: [port("w", 0, 24), port("e", 64, 24)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: CompressorSymbol,
  },
  {
    id: "heat-exchanger",
    category: "process",
    nameKey: "symbols.heatExchanger",
    defaultWidth: 80,
    defaultHeight: 48,
    ports: [port("w", 0, 24), port("e", 80, 24)],
    bindingSchema: [],
    render: HeatExchangerSymbol,
  },
  {
    id: "filter",
    category: "process",
    nameKey: "symbols.filter",
    defaultWidth: 48,
    defaultHeight: 56,
    ports: [port("n", 24, 0), port("s", 24, 56)],
    bindingSchema: [],
    render: FilterSymbol,
  },
  {
    id: "separator",
    category: "process",
    nameKey: "symbols.separator",
    defaultWidth: 56,
    defaultHeight: 72,
    ports: [port("n", 28, 0), port("s", 28, 72)],
    bindingSchema: [],
    render: SeparatorSymbol,
  },
  {
    id: "flare",
    category: "process",
    nameKey: "symbols.flare",
    defaultWidth: 32,
    defaultHeight: 48,
    ports: [port("s", 16, 48)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: FlareSymbol,
  },
  {
    id: "mixer",
    category: "process",
    nameKey: "symbols.mixer",
    defaultWidth: 48,
    defaultHeight: 48,
    ports: [port("w", 0, 24), port("e", 48, 24)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: MixerSymbol,
  },
  {
    id: "motor",
    category: "electrical",
    nameKey: "symbols.motor",
    defaultWidth: 48,
    defaultHeight: 48,
    ports: [port("n", 24, 0), port("s", 24, 48)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: MotorSymbol,
  },
  {
    id: "inverter",
    category: "electrical",
    nameKey: "symbols.inverter",
    defaultWidth: 64,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 64, 20)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: InverterSymbol,
  },
  {
    id: "capacitor",
    category: "electrical",
    nameKey: "symbols.capacitor",
    defaultWidth: 40,
    defaultHeight: 24,
    ports: [port("w", 0, 12), port("e", 40, 12)],
    bindingSchema: [],
    render: CapacitorSymbol,
  },
  {
    id: "reactor",
    category: "electrical",
    nameKey: "symbols.reactor",
    defaultWidth: 48,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 48, 16)],
    bindingSchema: [],
    render: ReactorSymbol,
  },
  {
    id: "transformer.three-winding",
    category: "electrical",
    nameKey: "symbols.transformerThreeWinding",
    defaultWidth: 72,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 72, 20)],
    bindingSchema: [],
    render: TransformerThreeWindingSymbol,
  },
  {
    id: "ground",
    category: "electrical",
    nameKey: "symbols.ground",
    defaultWidth: 32,
    defaultHeight: 32,
    ports: [port("n", 16, 0)],
    bindingSchema: [],
    render: GroundSymbol,
  },
  {
    id: "fuse",
    category: "electrical",
    nameKey: "symbols.fuse",
    defaultWidth: 24,
    defaultHeight: 48,
    ports: [port("n", 12, 0), port("s", 12, 48)],
    bindingSchema: [{ key: "blown", labelKey: "bindings.blown", type: "boolean" }],
    render: FuseSymbol,
  },
  {
    id: "contact",
    category: "electrical",
    nameKey: "symbols.contact",
    defaultWidth: 24,
    defaultHeight: 48,
    ports: [port("n", 12, 0), port("s", 12, 48)],
    bindingSchema: [{ key: "closed", labelKey: "bindings.closed", type: "boolean" }],
    render: ContactSymbol,
  },
  {
    id: "sensor.temperature",
    category: "process",
    nameKey: "symbols.sensorTemperature",
    defaultWidth: 40,
    defaultHeight: 40,
    ports: [],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: SensorTemperatureSymbol,
  },
  {
    id: "sensor.pressure",
    category: "process",
    nameKey: "symbols.sensorPressure",
    defaultWidth: 72,
    defaultHeight: 28,
    ports: [],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: SensorPressureSymbol,
  },
  {
    id: "alarm.banner",
    category: "common",
    nameKey: "symbols.alarmBanner",
    defaultWidth: 200,
    defaultHeight: 28,
    ports: [],
    bindingSchema: [
      { key: "active", labelKey: "bindings.active", type: "boolean" },
      { key: "text", labelKey: "bindings.text", type: "string", optional: true },
    ],
    render: AlarmBannerSymbol,
  },
  {
    id: "text.multiline",
    category: "common",
    nameKey: "symbols.textMultiline",
    defaultWidth: 160,
    defaultHeight: 48,
    ports: [],
    bindingSchema: [{ key: "text", labelKey: "bindings.text", type: "string" }],
    render: TextMultilineSymbol,
  },
  {
    id: "arrow",
    category: "common",
    nameKey: "symbols.arrow",
    defaultWidth: 48,
    defaultHeight: 16,
    ports: [port("w", 0, 8), port("e", 48, 8)],
    bindingSchema: [{ key: "right", labelKey: "bindings.right", type: "boolean", optional: true }],
    render: ArrowSymbol,
  },
  {
    id: "diamond",
    category: "common",
    nameKey: "symbols.diamond",
    defaultWidth: 48,
    defaultHeight: 48,
    ports: [],
    bindingSchema: [],
    render: DiamondSymbol,
  },
  {
    id: "valve.control",
    category: "process",
    nameKey: "symbols.valveControl",
    defaultWidth: 40,
    defaultHeight: 72,
    ports: [port("n", 20, 0), port("s", 20, 72)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveControlSymbol,
  },
  {
    id: "valve.safety",
    category: "process",
    nameKey: "symbols.valveSafety",
    defaultWidth: 32,
    defaultHeight: 56,
    ports: [port("n", 16, 0), port("s", 16, 56)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveSafetySymbol,
  },
  {
    id: "valve.needle",
    category: "process",
    nameKey: "symbols.valveNeedle",
    defaultWidth: 36,
    defaultHeight: 56,
    ports: [port("n", 18, 0), port("s", 18, 56)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveNeedleSymbol,
  },
  {
    id: "valve.diaphragm",
    category: "process",
    nameKey: "symbols.valveDiaphragm",
    defaultWidth: 36,
    defaultHeight: 56,
    ports: [port("n", 18, 0), port("s", 18, 56)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: ValveDiaphragmSymbol,
  },
  {
    id: "pipe.elbow",
    category: "process",
    nameKey: "symbols.pipeElbow",
    defaultWidth: 32,
    defaultHeight: 32,
    ports: [port("w", 4, 28), port("n", 28, 4)],
    bindingSchema: [],
    render: PipeElbowSymbol,
  },
  {
    id: "pipe.reducer",
    category: "process",
    nameKey: "symbols.pipeReducer",
    defaultWidth: 48,
    defaultHeight: 16,
    ports: [port("w", 0, 8), port("e", 48, 8)],
    bindingSchema: [],
    render: PipeReducerSymbol,
  },
  {
    id: "fan.blower",
    category: "process",
    nameKey: "symbols.fanBlower",
    defaultWidth: 48,
    defaultHeight: 48,
    ports: [port("w", 0, 24), port("e", 48, 24)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: FanBlowerSymbol,
  },
  {
    id: "column.distillation",
    category: "process",
    nameKey: "symbols.columnDistillation",
    defaultWidth: 40,
    defaultHeight: 120,
    ports: [port("n", 20, 0), port("s", 20, 120), port("e", 40, 60), port("w", 0, 60)],
    bindingSchema: [],
    render: ColumnDistillationSymbol,
  },
  {
    id: "boiler",
    category: "process",
    nameKey: "symbols.boiler",
    defaultWidth: 72,
    defaultHeight: 56,
    ports: [port("n", 36, 0), port("s", 36, 56), port("e", 72, 28), port("w", 0, 28)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: BoilerSymbol,
  },
  {
    id: "furnace",
    category: "process",
    nameKey: "symbols.furnace",
    defaultWidth: 64,
    defaultHeight: 56,
    ports: [port("n", 32, 0), port("s", 32, 56)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: FurnaceSymbol,
  },
  {
    id: "turbine.steam",
    category: "process",
    nameKey: "symbols.steamTurbine",
    defaultWidth: 56,
    defaultHeight: 56,
    ports: [port("w", 0, 28), port("e", 56, 28)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: SteamTurbineSymbol,
  },
  {
    id: "silo",
    category: "process",
    nameKey: "symbols.silo",
    defaultWidth: 56,
    defaultHeight: 72,
    ports: [port("n", 28, 0), port("s", 28, 72)],
    bindingSchema: [{ key: "fillLevel", labelKey: "bindings.fillLevel", type: "number" }],
    render: SiloSymbol,
  },
  {
    id: "hopper",
    category: "process",
    nameKey: "symbols.hopper",
    defaultWidth: 56,
    defaultHeight: 64,
    ports: [port("n", 28, 0), port("s", 28, 64)],
    bindingSchema: [],
    render: HopperSymbol,
  },
  {
    id: "conveyor",
    category: "process",
    nameKey: "symbols.conveyor",
    defaultWidth: 120,
    defaultHeight: 24,
    ports: [port("w", 0, 12), port("e", 120, 12)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: ConveyorSymbol,
  },
  {
    id: "agitator",
    category: "process",
    nameKey: "symbols.agitator",
    defaultWidth: 48,
    defaultHeight: 72,
    ports: [port("n", 24, 0), port("s", 24, 72)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: AgitatorSymbol,
  },
  {
    id: "orifice",
    category: "process",
    nameKey: "symbols.orifice",
    defaultWidth: 64,
    defaultHeight: 24,
    ports: [port("w", 0, 12), port("e", 64, 12)],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number", optional: true }],
    render: OrificeSymbol,
  },
  {
    id: "steam.trap",
    category: "process",
    nameKey: "symbols.steamTrap",
    defaultWidth: 28,
    defaultHeight: 48,
    ports: [port("n", 14, 0), port("s", 14, 48)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: SteamTrapSymbol,
  },
  {
    id: "vent",
    category: "process",
    nameKey: "symbols.vent",
    defaultWidth: 32,
    defaultHeight: 48,
    ports: [port("s", 16, 48)],
    bindingSchema: [],
    render: VentSymbol,
  },
  {
    id: "blind.flange",
    category: "process",
    nameKey: "symbols.blindFlange",
    defaultWidth: 32,
    defaultHeight: 24,
    ports: [port("w", 0, 12)],
    bindingSchema: [],
    render: BlindFlangeSymbol,
  },
  {
    id: "reactor.vessel",
    category: "process",
    nameKey: "symbols.reactorVessel",
    defaultWidth: 64,
    defaultHeight: 56,
    ports: [port("n", 32, 0), port("s", 32, 56), port("e", 64, 28), port("w", 0, 28)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: ReactorVesselSymbol,
  },
  {
    id: "damper",
    category: "process",
    nameKey: "symbols.damper",
    defaultWidth: 48,
    defaultHeight: 24,
    ports: [port("w", 0, 12), port("e", 48, 12)],
    bindingSchema: [{ key: "open", labelKey: "bindings.open", type: "boolean" }],
    render: DamperSymbol,
  },
  {
    id: "tank.conical",
    category: "process",
    nameKey: "symbols.tankConical",
    defaultWidth: 48,
    defaultHeight: 96,
    ports: [port("n", 24, 0), port("s", 24, 96), port("e", 48, 48), port("w", 0, 48)],
    bindingSchema: [{ key: "fillLevel", labelKey: "bindings.fillLevel", type: "number" }],
    render: TankConicalSymbol,
  },
  {
    id: "level.gauge",
    category: "process",
    nameKey: "symbols.levelGauge",
    defaultWidth: 24,
    defaultHeight: 64,
    ports: [],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: LevelGaugeSymbol,
  },
  {
    id: "relay",
    category: "electrical",
    nameKey: "symbols.relay",
    defaultWidth: 32,
    defaultHeight: 48,
    ports: [port("n", 16, 0), port("s", 16, 48)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: RelaySymbol,
  },
  {
    id: "switch.manual",
    category: "electrical",
    nameKey: "symbols.manualSwitch",
    defaultWidth: 24,
    defaultHeight: 52,
    ports: [port("n", 12, 0), port("s", 12, 52)],
    bindingSchema: [{ key: "closed", labelKey: "bindings.closed", type: "boolean" }],
    render: ManualSwitchSymbol,
  },
  {
    id: "lamp.pilot",
    category: "electrical",
    nameKey: "symbols.pilotLamp",
    defaultWidth: 24,
    defaultHeight: 24,
    ports: [],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: PilotLampSymbol,
  },
  {
    id: "ammeter",
    category: "electrical",
    nameKey: "symbols.ammeter",
    defaultWidth: 40,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 40, 20)],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: AmmeterSymbol,
  },
  {
    id: "voltmeter",
    category: "electrical",
    nameKey: "symbols.voltmeter",
    defaultWidth: 40,
    defaultHeight: 40,
    ports: [port("w", 0, 20), port("e", 40, 20)],
    bindingSchema: [{ key: "value", labelKey: "bindings.value", type: "number" }],
    render: VoltmeterSymbol,
  },
  {
    id: "ct",
    category: "electrical",
    nameKey: "symbols.ct",
    defaultWidth: 48,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 48, 16)],
    bindingSchema: [],
    render: CurrentTransformerSymbol,
  },
  {
    id: "pt",
    category: "electrical",
    nameKey: "symbols.pt",
    defaultWidth: 48,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 48, 16)],
    bindingSchema: [],
    render: PotentialTransformerSymbol,
  },
  {
    id: "arrester",
    category: "electrical",
    nameKey: "symbols.arrester",
    defaultWidth: 28,
    defaultHeight: 48,
    ports: [port("n", 14, 0), port("s", 14, 48)],
    bindingSchema: [],
    render: ArresterSymbol,
  },
  {
    id: "battery",
    category: "electrical",
    nameKey: "symbols.battery",
    defaultWidth: 48,
    defaultHeight: 28,
    ports: [port("w", 0, 14), port("e", 48, 14)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: BatterySymbol,
  },
  {
    id: "solar.panel",
    category: "electrical",
    nameKey: "symbols.solarPanel",
    defaultWidth: 64,
    defaultHeight: 40,
    ports: [port("e", 64, 20)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: SolarPanelSymbol,
  },
  {
    id: "wind.turbine",
    category: "electrical",
    nameKey: "symbols.windTurbine",
    defaultWidth: 40,
    defaultHeight: 56,
    ports: [port("s", 20, 56)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: WindTurbineSymbol,
  },
  {
    id: "ups",
    category: "electrical",
    nameKey: "symbols.ups",
    defaultWidth: 56,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 56, 16)],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: UpsSymbol,
  },
  {
    id: "starter.motor",
    category: "electrical",
    nameKey: "symbols.motorStarter",
    defaultWidth: 56,
    defaultHeight: 32,
    ports: [port("w", 0, 16), port("e", 56, 16)],
    bindingSchema: [{ key: "running", labelKey: "bindings.running", type: "boolean" }],
    render: MotorStarterSymbol,
  },
  {
    id: "plc",
    category: "electrical",
    nameKey: "symbols.plc",
    defaultWidth: 56,
    defaultHeight: 40,
    ports: [],
    bindingSchema: [{ key: "active", labelKey: "bindings.active", type: "boolean" }],
    render: PlcSymbol,
  },
  {
    id: "earthing.switch",
    category: "electrical",
    nameKey: "symbols.earthingSwitch",
    defaultWidth: 24,
    defaultHeight: 52,
    ports: [port("n", 12, 0), port("s", 12, 52)],
    bindingSchema: [{ key: "closed", labelKey: "bindings.closed", type: "boolean" }],
    render: EarthingSwitchSymbol,
  },
  {
    id: "line.h",
    category: "common",
    nameKey: "symbols.lineH",
    defaultWidth: 80,
    defaultHeight: 8,
    ports: [port("w", 0, 4), port("e", 80, 4)],
    bindingSchema: [],
    render: LineHorizontalSymbol,
  },
  {
    id: "line.v",
    category: "common",
    nameKey: "symbols.lineV",
    defaultWidth: 8,
    defaultHeight: 80,
    ports: [port("n", 4, 0), port("s", 4, 80)],
    bindingSchema: [],
    render: LineVerticalSymbol,
  },
  {
    id: "frame",
    category: "common",
    nameKey: "symbols.frame",
    defaultWidth: 160,
    defaultHeight: 96,
    ports: [],
    bindingSchema: [],
    render: FrameSymbol,
  },
  {
    id: "connector",
    category: "common",
    nameKey: "symbols.connector",
    defaultWidth: 16,
    defaultHeight: 16,
    ports: [port("n", 8, 0), port("s", 8, 16), port("e", 16, 8), port("w", 0, 8)],
    bindingSchema: [],
    render: ConnectorSymbol,
  },
  {
    id: "legend.box",
    category: "common",
    nameKey: "symbols.legendBox",
    defaultWidth: 160,
    defaultHeight: 64,
    ports: [],
    bindingSchema: [],
    render: LegendBoxSymbol,
  },
  {
    id: "callout",
    category: "common",
    nameKey: "symbols.callout",
    defaultWidth: 120,
    defaultHeight: 48,
    ports: [],
    bindingSchema: [{ key: "text", labelKey: "bindings.text", type: "string", optional: true }],
    render: CalloutSymbol,
  },
  ...(DOMAIN_SYMBOLS as RegisteredSymbol[]),
];

const byId = new Map(SYMBOLS.map((s) => [s.id, s]));

export const SYMBOL_CATALOG: SymbolDefinition[] = SYMBOLS;

export function getSymbol(id: string): RegisteredSymbol | undefined {
  return byId.get(id);
}

export function getSymbolRender(id: string): ComponentType<SymbolRenderProps> | undefined {
  return byId.get(id)?.render;
}

export function listSymbolsByCategory(category: string): RegisteredSymbol[] {
  return SYMBOLS.filter((s) => s.category === category);
}

export function listAllSymbols(): RegisteredSymbol[] {
  return SYMBOLS;
}

export const SYMBOL_CATEGORIES = ["process", "electrical", "common", ...DOMAIN_CATEGORY_IDS] as const;

export function symbolSize(element: { symbolId: string; scale?: number; props?: Record<string, unknown> }) {
  const sym = getSymbol(element.symbolId);
  const scale = element.scale ?? 1;
  const propW = typeof element.props?.width === "number" ? element.props.width : Number(element.props?.width);
  const propH = typeof element.props?.height === "number" ? element.props.height : Number(element.props?.height);
  return {
    width: (Number.isFinite(propW) && propW > 0 ? propW : (sym?.defaultWidth ?? 64)) * scale,
    height: (Number.isFinite(propH) && propH > 0 ? propH : (sym?.defaultHeight ?? 64)) * scale,
  };
}
