#!/usr/bin/env bash
# Shared MQTT/loadgen + remote DB settings for lab LAN.
set -euo pipefail

LAB_LOADGEN_ENV="${ISPF_LAB_LOADGEN_ENV:-${ISPF_LAB_ROOT:-$HOME/ispf}/lab-loadgen.env}"
if [[ -f "${LAB_LOADGEN_ENV}" ]]; then
  # shellcheck disable=SC1090
  set -a && source "${LAB_LOADGEN_ENV}" && set +a
fi

ISPF_LAB_LOADGEN_HOST="${ISPF_LAB_LOADGEN_HOST:-198.51.100.10}"
ISPF_LAB_CLUSTER_HOST="${ISPF_LAB_CLUSTER_HOST:-198.51.100.11}"
ISPF_LAB_LOADGEN_SSH="${ISPF_LAB_LOADGEN_SSH:-lab-operator@${ISPF_LAB_LOADGEN_HOST}}"
ISPF_LAB_LOADGEN_ROOT="${ISPF_LAB_LOADGEN_ROOT:-/home/lab-operator/ispf}"
ISPF_MQTT_BROKER_HOST="${ISPF_MQTT_BROKER_HOST:-${ISPF_LAB_LOADGEN_HOST}}"
ISPF_MQTT_BROKER_PORT="${ISPF_MQTT_BROKER_PORT:-1883}"

ISPF_LAB_DB_HOST="${ISPF_LAB_DB_HOST:-${ISPF_LAB_LOADGEN_HOST}}"
ISPF_LAB_DB_BIND="${ISPF_LAB_DB_BIND:-${ISPF_LAB_DB_HOST}}"
ISPF_LAB_DB_SSH="${ISPF_LAB_DB_SSH:-lab-operator@${ISPF_LAB_DB_HOST}}"
ISPF_LAB_DB_SCYLLA_CONTAINER="${ISPF_LAB_DB_SCYLLA_CONTAINER:-ispf-db-scylla-1}"

MQTT_BROKER_URL="tcp://${ISPF_MQTT_BROKER_HOST}:${ISPF_MQTT_BROKER_PORT}"
MQTT_PUBLISH_HOST="${MQTT_PUBLISH_HOST:-127.0.0.1}"
MQTT_PUBLISH_PORT="${MQTT_PUBLISH_PORT:-1883}"

LOADGEN_COMPOSE_FILE="${ISPF_LAB_LOADGEN_ROOT}/lab-loadgen-compose.yml"
LOADGEN_MQTT_CONTAINER="${LOADGEN_MQTT_CONTAINER:-ispf-loadgen-mqtt-1}"
