plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

rootProject.name = "iot-solutions-platform-framework"

include(
    "packages:ispf-core",
    "packages:ispf-expression",
    "packages:ispf-driver-api",
    "packages:ispf-server",
    "packages:ispf-driver-mqtt",
    "packages:ispf-driver-modbus",
    "packages:ispf-driver-snmp",
    "packages:ispf-driver-virtual",
    "packages:ispf-driver-http",
    "packages:ispf-driver-icmp",
    "packages:ispf-driver-ssh",
    "packages:ispf-driver-coap",
    "packages:ispf-driver-opcua",
    "packages:ispf-driver-s7",
    "packages:ispf-driver-iec104",
    "packages:ispf-driver-bacnet",
    "packages:ispf-driver-dnp3",
    "packages:ispf-driver-jmx",
    "packages:ispf-driver-jdbc",
    "packages:ispf-driver-file",
    "packages:ispf-driver-folder",
    "packages:ispf-driver-application",
    "packages:ispf-driver-message-stream",
    "packages:ispf-driver-nmea",
    "packages:ispf-driver-telnet",
    "packages:ispf-driver-soap",
    "packages:ispf-driver-ip-host",
    "packages:ispf-driver-kafka",
    "packages:ispf-driver-gps-tracker",
    "packages:ispf-driver-flexible",
    "packages:ispf-driver-mbus",
    "packages:ispf-driver-omron-fins",
    "packages:ispf-driver-asterisk",
    "packages:ispf-driver-smpp",
    "packages:ispf-driver-smb",
    "packages:ispf-plugin-model",
    "packages:ispf-plugin-workflow",
)
