
SELECT domain, activity, status, COALESCE(note, '') AS note, COALESCE(ui_link, '') AS ui_link
FROM emc_mom_activity
ORDER BY CASE domain
  WHEN 'PRODUCTION' THEN 1 WHEN 'QUALITY' THEN 2 WHEN 'INVENTORY' THEN 3 ELSE 4 END,
  CASE activity
  WHEN 'DEFINITION' THEN 1 WHEN 'RESOURCE' THEN 2 WHEN 'DETAILED_SCHEDULING' THEN 3
  WHEN 'DISPATCHING' THEN 4 WHEN 'EXECUTION' THEN 5 WHEN 'DATA_COLLECTION' THEN 6
  WHEN 'TRACKING' THEN 7 ELSE 8 END
