-- ISPF platform relational schema (greenfield baseline, ADR-0037)
-- Squashed from incremental V1-V70; new installs only — no upgrade path from legacy versions.

-- ===== V1__init_schema.sql =====
CREATE TABLE IF NOT EXISTS object_nodes (
    id           VARCHAR(64)  PRIMARY KEY,
    path         VARCHAR(512) NOT NULL UNIQUE,
    type         VARCHAR(32)  NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    description  TEXT,
    template_id  VARCHAR(128),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    events_json  TEXT,
    functions_json TEXT
);

CREATE TABLE IF NOT EXISTS object_variables (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_path VARCHAR(512) NOT NULL,
    name         VARCHAR(128) NOT NULL,
    schema_json  TEXT         NOT NULL,
    value_json   TEXT,
    readable     BOOLEAN      NOT NULL DEFAULT TRUE,
    writable     BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMP,
    UNIQUE (object_path, name)
);

CREATE TABLE IF NOT EXISTS event_history (
    id           VARCHAR(64)  PRIMARY KEY,
    object_path VARCHAR(512) NOT NULL,
    event_name   VARCHAR(128) NOT NULL,
    level        VARCHAR(16)  NOT NULL,
    payload_json TEXT,
    occurred_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_history_object ON event_history(object_path, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_object_variables_path ON object_variables(object_path);


-- ===== V2__workflow_instances.sql =====
-- Workflow v2: persistent instances and operator work queue

CREATE TABLE IF NOT EXISTS workflow_instances (
    id              VARCHAR(64)  PRIMARY KEY,
    workflow_path   VARCHAR(512) NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    current_node_id VARCHAR(128),
    assignee        VARCHAR(128),
    trigger_object_path VARCHAR(512),
    state_json      TEXT,
    started_at      TIMESTAMP    NOT NULL,
    completed_at    TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflow_user_tasks (
    id              VARCHAR(64)  PRIMARY KEY,
    instance_id     VARCHAR(64)  NOT NULL,
    workflow_path   VARCHAR(512) NOT NULL,
    task_node_id    VARCHAR(128) NOT NULL,
    title           VARCHAR(256) NOT NULL,
    instructions    TEXT,
    assignee_role   VARCHAR(64)  NOT NULL DEFAULT 'operator',
    status          VARCHAR(16)  NOT NULL,
    assignee        VARCHAR(128),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_at      TIMESTAMP,
    completed_at    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_workflow_instances_path ON workflow_instances(workflow_path, status);
CREATE INDEX IF NOT EXISTS idx_workflow_user_tasks_status ON workflow_user_tasks(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflow_user_tasks_instance ON workflow_user_tasks(instance_id);


-- ===== V3__alert_rules.sql =====
CREATE TABLE IF NOT EXISTS alert_rules (
    id                 VARCHAR(64)  PRIMARY KEY,
    name               VARCHAR(256) NOT NULL,
    object_path       VARCHAR(512) NOT NULL,
    watch_variable     VARCHAR(128) NOT NULL,
    condition_expr     TEXT         NOT NULL,
    event_name         VARCHAR(128) NOT NULL,
    payload_variable   VARCHAR(128),
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    edge_trigger       BOOLEAN      NOT NULL DEFAULT TRUE,
    last_condition_met BOOLEAN,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_rules_object ON alert_rules(object_path, watch_variable);


-- ===== V4__event_correlators.sql =====
CREATE TABLE IF NOT EXISTS event_correlators (
    id                 VARCHAR(64)  PRIMARY KEY,
    name               VARCHAR(256) NOT NULL,
    object_path       VARCHAR(512),
    event_name         VARCHAR(128) NOT NULL,
    window_seconds     INT          NOT NULL DEFAULT 0,
    min_occurrences    INT          NOT NULL DEFAULT 1,
    cooldown_seconds   INT          NOT NULL DEFAULT 60,
    action_type        VARCHAR(32)  NOT NULL,
    action_target      VARCHAR(512) NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    last_triggered_at  TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_correlators_match
    ON event_correlators(event_name, enabled);

CREATE TABLE IF NOT EXISTS correlator_hits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlator_id  VARCHAR(64)  NOT NULL,
    object_path   VARCHAR(512) NOT NULL,
    occurred_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_correlator_hits_window
    ON correlator_hits(correlator_id, occurred_at DESC);


-- ===== V5__correlator_patterns.sql =====
-- Multi-event correlator patterns (COUNT | SEQUENCE)

ALTER TABLE event_correlators
    ADD COLUMN IF NOT EXISTS pattern_type VARCHAR(32) NOT NULL DEFAULT 'COUNT';

ALTER TABLE event_correlators
    ADD COLUMN IF NOT EXISTS second_event_name VARCHAR(128);

ALTER TABLE correlator_hits
    ADD COLUMN IF NOT EXISTS event_name VARCHAR(128);


-- ===== V10__application_platform.sql =====
CREATE TABLE applications (
    app_id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    table_prefix VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE application_data_migrations (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    version VARCHAR(64) NOT NULL,
    script_id VARCHAR(128) NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_migration UNIQUE (app_id, version, script_id)
);

CREATE TABLE application_functions (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    object_path VARCHAR(512) NOT NULL,
    function_name VARCHAR(128) NOT NULL,
    version VARCHAR(64) NOT NULL DEFAULT '1',
    source_type VARCHAR(32) NOT NULL,
    source_body TEXT NOT NULL,
    input_schema_json TEXT NOT NULL,
    output_schema_json TEXT NOT NULL,
    deployed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_function UNIQUE (app_id, object_path, function_name, version)
);

CREATE TABLE platform_schedules (
    schedule_id VARCHAR(128) PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    interval_ms BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    action_json TEXT NOT NULL,
    last_tick_at TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE model_definitions (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    definition_json TEXT NOT NULL,
    builtin BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE function_invoke_audit (
    id UUID PRIMARY KEY,
    correlation_id VARCHAR(64),
    object_path VARCHAR(512),
    function_name VARCHAR(128),
    app_id VARCHAR(64),
    success BOOLEAN NOT NULL,
    error_message VARCHAR(1024),
    invoked_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE workflow_cancel_journal (
    id UUID PRIMARY KEY,
    instance_id VARCHAR(64) NOT NULL,
    workflow_path VARCHAR(512) NOT NULL,
    reason VARCHAR(128) NOT NULL,
    detail_json TEXT,
    cancelled_by VARCHAR(128),
    cancelled_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ===== V11__application_schema_seeds.sql =====
ALTER TABLE applications ADD COLUMN IF NOT EXISTS schema_name VARCHAR(64);

CREATE TABLE IF NOT EXISTS application_data_seeds (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    profile VARCHAR(64) NOT NULL,
    seed_id VARCHAR(128) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_seed UNIQUE (app_id, profile, seed_id)
);


-- ===== V12__application_sql_bindings.sql =====
CREATE TABLE application_sql_bindings (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    object_path VARCHAR(512) NOT NULL,
    variable_name VARCHAR(128) NOT NULL,
    query_sql TEXT NOT NULL,
    refresh_mode VARCHAR(32) NOT NULL DEFAULT 'on_schedule',
    refresh_interval_ms BIGINT,
    value_field VARCHAR(128) DEFAULT 'value',
    trigger_object_path VARCHAR(512),
    trigger_function_name VARCHAR(128),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_refreshed_at TIMESTAMP,
    deployed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_sql_binding UNIQUE (app_id, object_path, variable_name)
);


-- ===== V13__application_bundle_deployments.sql =====
CREATE TABLE application_bundle_deployments (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    bundle_version VARCHAR(64) NOT NULL,
    manifest_json TEXT NOT NULL,
    operator_manifest_json TEXT,
    deployed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_app_bundle_version UNIQUE (app_id, bundle_version)
);

CREATE INDEX idx_app_bundle_active ON application_bundle_deployments (app_id, is_active);


-- ===== V14__application_reports.sql =====
CREATE TABLE application_reports (
    id UUID PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id),
    report_id VARCHAR(128) NOT NULL,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    query_sql TEXT NOT NULL,
    parameters_json TEXT,
    columns_json TEXT NOT NULL,
    max_rows INTEGER NOT NULL DEFAULT 1000,
    deployed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_app_report UNIQUE (app_id, report_id)
);


-- ===== V15__platform_users.sql =====
CREATE TABLE platform_users (
    username VARCHAR(64) PRIMARY KEY,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    roles_json VARCHAR(255) NOT NULL,
    object_path VARCHAR(512) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE platform_auth_sessions (
    token VARCHAR(64) PRIMARY KEY,
    username VARCHAR(64) NOT NULL REFERENCES platform_users(username) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_platform_auth_sessions_username ON platform_auth_sessions(username);
CREATE INDEX idx_platform_auth_sessions_expires ON platform_auth_sessions(expires_at);


-- ===== V16__user_auto_start_app.sql =====
ALTER TABLE platform_users
    ADD COLUMN auto_start_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE platform_users
    ADD COLUMN auto_start_app VARCHAR(128);


-- ===== V17__operator_app_ui.sql =====
CREATE TABLE operator_app_ui (
    app_id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    default_dashboard VARCHAR(512),
    dashboards_json TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);


-- ===== V18__variable_samples.sql =====
-- Time-series samples for platform object variables (telemetry historian).
-- PostgreSQL: optional Timescale hypertable вЂ” SELECT create_hypertable('variable_samples', 'sampled_at', if_not_exists => TRUE);

CREATE TABLE IF NOT EXISTS variable_samples (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_path   VARCHAR(512) NOT NULL,
    variable_name VARCHAR(128) NOT NULL,
    field_name    VARCHAR(128) NOT NULL DEFAULT 'value',
    sampled_at    TIMESTAMP    NOT NULL,
    value_double  DOUBLE PRECISION,
    value_text    VARCHAR(2048)
);

CREATE INDEX IF NOT EXISTS idx_variable_samples_lookup
    ON variable_samples (object_path, variable_name, field_name, sampled_at DESC);

CREATE INDEX IF NOT EXISTS idx_variable_samples_retention
    ON variable_samples (sampled_at);


-- ===== V19__variable_history_metadata.sql =====
ALTER TABLE object_variables
    ADD COLUMN history_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE object_variables
    ADD COLUMN history_retention_days INTEGER;

-- Backfill known telemetry variables created before per-variable history metadata.
UPDATE object_variables
SET history_enabled = TRUE
WHERE name IN (
    'temperature',
    'sysUpTime',
    'hrMemorySize',
    'hrSystemProcesses',
    'hrSystemNumUsers',
    'ifNumber',
    'ifInOctets',
    'ifOutOctets',
    'hrProcessorLoad'
);


-- ===== V20__platform_roles.sql =====
CREATE TABLE platform_roles (
    name VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL DEFAULT '',
    built_in BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO platform_roles (name, display_name, description, built_in)
VALUES
    ('admin', 'admin', 'Full platform administration', TRUE),
    ('operator', 'operator', 'Operator HMI and read-only automation', TRUE);


-- ===== V21__object_tree_sort_order.sql =====
ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;


-- ===== V22__system_object_types.sql =====
UPDATE object_nodes SET type = 'PLATFORM' WHERE path = 'root.platform';
UPDATE object_nodes SET type = 'DEVICES' WHERE path = 'root.platform.devices';
UPDATE object_nodes SET type = 'DASHBOARDS' WHERE path = 'root.platform.dashboards';
UPDATE object_nodes SET type = 'WORKFLOWS' WHERE path = 'root.platform.workflows';
UPDATE object_nodes SET type = 'ALERT_RULES' WHERE path = 'root.platform.alert-rules';
UPDATE object_nodes SET type = 'CORRELATORS' WHERE path = 'root.platform.correlators';
UPDATE object_nodes SET type = 'APPLICATIONS' WHERE path = 'root.platform.applications';
UPDATE object_nodes SET type = 'OPERATOR_APPS' WHERE path = 'root.platform.operator-apps';
UPDATE object_nodes SET type = 'SECURITY' WHERE path = 'root.platform.security';
UPDATE object_nodes SET type = 'USERS' WHERE path = 'root.platform.security.users';
UPDATE object_nodes SET type = 'ROLES' WHERE path = 'root.platform.security.roles';

UPDATE object_nodes SET type = 'ROLE' WHERE template_id = 'platform-role-v1';
UPDATE object_nodes SET type = 'FUNCTION' WHERE template_id = 'application-function-v1';
UPDATE object_nodes SET type = 'SCHEDULE' WHERE template_id = 'application-schedule-v1';
UPDATE object_nodes SET type = 'BINDING' WHERE template_id = 'application-binding-v1';
UPDATE object_nodes SET type = 'MIGRATION' WHERE template_id = 'application-migration-v1';
UPDATE object_nodes SET type = 'SCREEN' WHERE template_id = 'operator-screen-v1';

UPDATE object_nodes SET type = 'REPORTS' WHERE path LIKE '%.reports' AND type = 'CUSTOM';
UPDATE object_nodes SET type = 'FUNCTIONS' WHERE path LIKE '%.functions' AND type = 'CUSTOM';
UPDATE object_nodes SET type = 'SCHEDULES' WHERE path LIKE '%.schedules' AND type = 'CUSTOM';
UPDATE object_nodes SET type = 'BINDINGS' WHERE path LIKE '%.bindings' AND type = 'CUSTOM';
UPDATE object_nodes SET type = 'MIGRATIONS' WHERE path LIKE '%.migrations' AND type = 'CUSTOM';
UPDATE object_nodes SET type = 'SCREENS' WHERE path LIKE '%.screens' AND type = 'CUSTOM';


-- ===== V23__platform_leader_locks.sql =====
CREATE TABLE platform_leader_locks (
    lock_name   VARCHAR(128) PRIMARY KEY,
    holder_id   VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL
);


-- ===== V25__object_acl.sql =====
CREATE TABLE IF NOT EXISTS object_acl_entries (
    id              UUID PRIMARY KEY,
    object_path     VARCHAR(512) NOT NULL,
    principal_type  VARCHAR(16)  NOT NULL,
    principal_id    VARCHAR(128) NOT NULL,
    permission      VARCHAR(16)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_object_acl_path ON object_acl_entries (object_path);
CREATE UNIQUE INDEX IF NOT EXISTS uq_object_acl_grant
    ON object_acl_entries (object_path, principal_type, principal_id, permission);


-- ===== V26__federation_peers.sql =====
CREATE TABLE IF NOT EXISTS federation_peers (
    id           UUID PRIMARY KEY,
    name         VARCHAR(128) NOT NULL,
    base_url     VARCHAR(512) NOT NULL,
    auth_token   VARCHAR(512),
    path_prefix  VARCHAR(256) NOT NULL DEFAULT '',
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    description  VARCHAR(1024),
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_federation_peer_name ON federation_peers (name);


-- ===== V27__platform_tenants.sql =====
CREATE TABLE IF NOT EXISTS platform_tenants (
    tenant_id    VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

ALTER TABLE platform_users ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_platform_users_tenant ON platform_users (tenant_id);


-- ===== V28__snmp_rate_variable_history.sql =====
-- Enable historian for SNMP rate variables derived from Counter32 bindings.
UPDATE object_variables
SET history_enabled = TRUE
WHERE name IN ('ifInOctetsRate', 'ifOutOctetsRate');


-- ===== V29__federation_peer_auth.sql =====
ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS connection_mode VARCHAR(32) NOT NULL DEFAULT 'HTTP_PULL';

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS auth_mode VARCHAR(32) NOT NULL DEFAULT 'STATIC_TOKEN';

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS token_expires_at TIMESTAMP;

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS auth_username VARCHAR(128);

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS auth_secret_enc VARCHAR(1024);

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS auth_status VARCHAR(32) NOT NULL DEFAULT 'OK';

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS last_auth_at TIMESTAMP;

ALTER TABLE federation_peers
    ADD COLUMN IF NOT EXISTS last_auth_error VARCHAR(1024);


-- ===== V30__federation_tunnel.sql =====
CREATE TABLE IF NOT EXISTS federation_inbound_registrations (
    id                      UUID PRIMARY KEY,
    name                    VARCHAR(128) NOT NULL,
    registration_code_hash  VARCHAR(128) NOT NULL,
    path_prefix             VARCHAR(256) NOT NULL DEFAULT 'root.platform',
    expires_at              TIMESTAMP NOT NULL,
    consumed_at             TIMESTAMP,
    created_by              VARCHAR(128),
    created_at              TIMESTAMP NOT NULL,
    updated_at              TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_federation_inbound_reg_name
    ON federation_inbound_registrations (name);

CREATE TABLE IF NOT EXISTS federation_outbound_agents (
    id                  UUID PRIMARY KEY,
    name                VARCHAR(128) NOT NULL,
    hub_base_url        VARCHAR(512) NOT NULL,
    registration_code_enc VARCHAR(1024),
    session_token_enc   VARCHAR(1024),
    path_prefix         VARCHAR(256) NOT NULL DEFAULT 'root.platform',
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    tunnel_status       VARCHAR(32) NOT NULL DEFAULT 'DISCONNECTED',
    linked_peer_id      UUID,
    last_error          VARCHAR(1024),
    last_connected_at   TIMESTAMP,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_federation_outbound_agent_name
    ON federation_outbound_agents (name);

CREATE TABLE IF NOT EXISTS federation_tunnel_sessions (
    session_id          VARCHAR(64) PRIMARY KEY,
    registration_id     UUID,
    peer_id             UUID NOT NULL,
    connected_at        TIMESTAMP NOT NULL,
    last_ping_at        TIMESTAMP NOT NULL,
    agent_version       VARCHAR(64),
    disconnected_at     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_federation_tunnel_sessions_peer
    ON federation_tunnel_sessions (peer_id);


-- ===== V31__platform_federation_secrets.sql =====
CREATE TABLE IF NOT EXISTS platform_federation_secrets (
    id           CHAR(1) NOT NULL PRIMARY KEY,
    secrets_key  VARCHAR(512) NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT platform_federation_secrets_singleton CHECK (id = 'X')
);


-- ===== V32__collaboration.sql =====
ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS last_changed_by VARCHAR(128);
ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS last_changed_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS object_config_audit (
    id              VARCHAR(64)  PRIMARY KEY,
    object_path     VARCHAR(512) NOT NULL,
    change_type     VARCHAR(64)  NOT NULL,
    field           VARCHAR(256),
    actor           VARCHAR(128),
    occurred_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revision_before BIGINT,
    revision_after  BIGINT,
    summary_json    TEXT
);

CREATE INDEX IF NOT EXISTS idx_object_config_audit_path
    ON object_config_audit (object_path, occurred_at DESC);

CREATE TABLE IF NOT EXISTS object_edit_leases (
    id           VARCHAR(64)  PRIMARY KEY,
    path_prefix  VARCHAR(512) NOT NULL UNIQUE,
    holder       VARCHAR(128) NOT NULL,
    expires_at   TIMESTAMP    NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_object_edit_leases_expires
    ON object_edit_leases (expires_at);

CREATE TABLE IF NOT EXISTS platform_change_sets (
    id              VARCHAR(64)  PRIMARY KEY,
    title           VARCHAR(256) NOT NULL,
    author          VARCHAR(128) NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'DRAFT',
    base_snapshot   TEXT,
    ops_json        TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_platform_change_sets_status
    ON platform_change_sets (status, updated_at DESC);


-- ===== V33__reports_tree_first.sql =====
UPDATE object_nodes SET type = 'REPORTS' WHERE path = 'root.platform.reports';

UPDATE object_nodes SET type = 'REPORT' WHERE template_id = 'report-v1';

DELETE FROM object_variables
WHERE object_path IN (
    SELECT path FROM object_nodes
    WHERE path LIKE 'root.platform.applications.%.reports.%'
);

DELETE FROM object_nodes
WHERE path LIKE 'root.platform.applications.%.reports.%';

DELETE FROM object_nodes
WHERE path LIKE 'root.platform.applications.%.reports'
  AND type IN ('REPORTS', 'CUSTOM');


-- ===== V34__report_templates.sql =====
CREATE TABLE report_templates (
    report_path VARCHAR(512) PRIMARY KEY,
    format      VARCHAR(16)  NOT NULL,
    content     BYTEA NOT NULL,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ===== V35__object_nodes_type_index.sql =====
CREATE INDEX IF NOT EXISTS idx_object_nodes_type ON object_nodes (type);
CREATE INDEX IF NOT EXISTS idx_object_nodes_path_prefix ON object_nodes (path);


-- ===== V36__application_event_catalog.sql =====
CREATE TABLE application_event_catalog (
    app_id VARCHAR(64) NOT NULL REFERENCES applications(app_id) ON DELETE CASCADE,
    event_id VARCHAR(128) NOT NULL,
    roles_json TEXT NOT NULL DEFAULT '[]',
    payload_schema_json TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (app_id, event_id)
);

CREATE INDEX idx_application_event_catalog_app ON application_event_catalog (app_id);


-- ===== V37__ai_tool_audit.sql =====
CREATE TABLE ai_tool_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR(64) NOT NULL,
    app_id VARCHAR(128),
    actor VARCHAR(128),
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_id VARCHAR(64),
    model_id VARCHAR(128),
    context_pack_version VARCHAR(64),
    errors_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_ai_tool_audit_created_at ON ai_tool_audit (created_at DESC);
CREATE INDEX idx_ai_tool_audit_app_id ON ai_tool_audit (app_id);


-- ===== V38__agent_sessions.sql =====
CREATE TABLE agent_sessions (
    session_id   VARCHAR(64)  PRIMARY KEY,
    actor        VARCHAR(128) NOT NULL,
    root_path    VARCHAR(512) NOT NULL,
    title        VARCHAR(256) NOT NULL,
    run_state_json TEXT,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL
);

CREATE INDEX idx_agent_sessions_actor_updated ON agent_sessions (actor, updated_at DESC);

CREATE TABLE agent_turns (
    turn_id            VARCHAR(64) PRIMARY KEY,
    session_id         VARCHAR(64) NOT NULL,
    user_message       TEXT,
    assistant_summary  TEXT,
    status             VARCHAR(16) NOT NULL,
    steps_json         TEXT,
    result_json        TEXT,
    created_at         TIMESTAMP   NOT NULL,
    sort_order         INT         NOT NULL,
    CONSTRAINT fk_agent_turns_session FOREIGN KEY (session_id) REFERENCES agent_sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX idx_agent_turns_session_order ON agent_turns (session_id, sort_order);


-- ===== V39__object_applied_models.sql =====
ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS applied_model_ids TEXT;

UPDATE object_nodes
SET applied_model_ids = '["' || REPLACE(template_id, '"', '\"') || '"]'
WHERE template_id IS NOT NULL
  AND template_id <> ''
  AND (applied_model_ids IS NULL OR TRIM(applied_model_ids) = '');


-- ===== V40__operator_app_ui_extras.sql =====
ALTER TABLE operator_app_ui ADD COLUMN IF NOT EXISTS ui_extras_json TEXT;


-- ===== V41__drop_binding_expr.sql =====
-- 0010 / Phase 17.2: binding rules only; legacy column removed.
-- Fresh installs: column absent from V1. Existing DBs: drop after recreate or via this migration.
ALTER TABLE object_variables DROP COLUMN IF EXISTS binding_expr;


-- ===== V42__workflow_operator_app.sql =====
-- Snapshot operator app on work queue tasks (from workflow.operatorAppId at task creation)

ALTER TABLE workflow_user_tasks
    ADD COLUMN IF NOT EXISTS operator_app_id VARCHAR(128);

CREATE INDEX IF NOT EXISTS idx_workflow_user_tasks_operator_app
    ON workflow_user_tasks(operator_app_id, status, created_at DESC);


-- ===== V43__platform_catalog_sort_order.sql =====
-- Default platform catalog folder order (matches production VPS layout).
UPDATE object_nodes SET sort_order = 0 WHERE path = 'root.platform.security';
UPDATE object_nodes SET sort_order = 1 WHERE path = 'root.platform.devices';
UPDATE object_nodes SET sort_order = 2 WHERE path = 'root.platform.alert-rules';
UPDATE object_nodes SET sort_order = 3 WHERE path = 'root.platform.operator-apps';
UPDATE object_nodes SET sort_order = 4 WHERE path = 'root.platform.dashboards';
UPDATE object_nodes SET sort_order = 5 WHERE path = 'root.platform.relative-models';
UPDATE object_nodes SET sort_order = 6 WHERE path = 'root.platform.absolute-models';
UPDATE object_nodes SET sort_order = 7 WHERE path = 'root.platform.instance-types';
UPDATE object_nodes SET sort_order = 8 WHERE path = 'root.platform.reports';
UPDATE object_nodes SET sort_order = 9 WHERE path = 'root.platform.correlators';
UPDATE object_nodes SET sort_order = 10 WHERE path = 'root.platform.workflows';
UPDATE object_nodes SET sort_order = 11 WHERE path = 'root.platform.schedules';
UPDATE object_nodes SET sort_order = 12 WHERE path = 'root.platform.data-sources';
UPDATE object_nodes SET sort_order = 13 WHERE path = 'root.platform.bindings';
UPDATE object_nodes SET sort_order = 14 WHERE path = 'root.platform.migrations';
UPDATE object_nodes SET sort_order = 15 WHERE path = 'root.platform.federation';
UPDATE object_nodes SET sort_order = 16 WHERE path = 'root.platform.applications';
UPDATE object_nodes SET sort_order = 17 WHERE path = 'root.platform.instances';
UPDATE object_nodes SET sort_order = 0 WHERE path = 'root.platform';
UPDATE object_nodes SET sort_order = 1 WHERE path = 'root.tenant';


-- ===== V44__correlator_hits_composite_index.sql =====
CREATE INDEX IF NOT EXISTS idx_correlator_hits_lookup
  ON correlator_hits (correlator_id, object_path, event_name, occurred_at DESC);


-- ===== V45__system_intrinsic_models.sql =====
-- Remove system-intrinsic model catalog nodes (schemas are embedded in object instances).
DELETE FROM object_nodes
WHERE path IN (
    'root.platform.relative-models.data-source-v1',
    'root.platform.relative-models.schedule-v1',
    'root.platform.relative-models.sql-binding-v1',
    'root.platform.relative-models.migration-v1',
    'root.platform.relative-models.alert-rule-v1',
    'root.platform.relative-models.correlator-v1',
    'root.platform.relative-models.dashboard-v1',
    'root.platform.relative-models.report-v1',
    'root.platform.relative-models.workflow-v1'
);


-- ===== V46__event_history_occurred_at_index.sql =====
CREATE INDEX IF NOT EXISTS idx_event_history_occurred_at ON event_history(occurred_at DESC);


-- ===== V47__event_history_timescale.sql =====
-- Event journal (alert fires, API events). Append-only time series.
-- Timescale hypertable: create_hypertable('event_history', 'occurred_at') at startup when extension is present.

-- idx_event_history_occurred_at (V46) and idx_event_history_object (V1) support time-ordered queries.


-- ===== V48__binding_invoke_audit.sql =====
CREATE TABLE binding_invoke_audit (
    id UUID PRIMARY KEY,
    binding_kind VARCHAR(16) NOT NULL,
    object_path VARCHAR(512) NOT NULL,
    rule_id VARCHAR(128),
    rule_name VARCHAR(255),
    trigger_kind VARCHAR(32) NOT NULL,
    target_variable VARCHAR(128),
    success BOOLEAN NOT NULL,
    changed BOOLEAN NOT NULL DEFAULT FALSE,
    error_message VARCHAR(1024),
    duration_ms INTEGER,
    invoked_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_binding_invoke_audit_object_path ON binding_invoke_audit (object_path, invoked_at DESC);
CREATE INDEX idx_binding_invoke_audit_invoked_at ON binding_invoke_audit (invoked_at DESC);


-- ===== V49__object_binding_audit_flag.sql =====
ALTER TABLE object_nodes
    ADD COLUMN IF NOT EXISTS binding_audit_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_object_nodes_binding_audit_enabled
    ON object_nodes (binding_audit_enabled);


-- ===== V50__object_function_audit_flag.sql =====
ALTER TABLE object_nodes
    ADD COLUMN IF NOT EXISTS function_audit_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_object_nodes_function_audit_enabled
    ON object_nodes (function_audit_enabled);


-- ===== V51__journal_audit_details.sql =====
ALTER TABLE function_invoke_audit ADD COLUMN IF NOT EXISTS input_json TEXT;
ALTER TABLE function_invoke_audit ADD COLUMN IF NOT EXISTS output_json TEXT;

ALTER TABLE binding_invoke_audit ADD COLUMN IF NOT EXISTS detail_json TEXT;


-- ===== V52__operator_agent_memory.sql =====
-- Long-lived knowledge per operator application (shared across operators of the app).
CREATE TABLE operator_agent_memory (
    memory_id     VARCHAR(64)  PRIMARY KEY,
    app_id        VARCHAR(128) NOT NULL,
    kind          VARCHAR(32)  NOT NULL,
    topic         VARCHAR(256) NOT NULL,
    content       TEXT         NOT NULL,
    source_actor  VARCHAR(128),
    source_turn_id VARCHAR(64),
    use_count     INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_operator_agent_memory_app_topic UNIQUE (app_id, topic)
);

CREATE INDEX idx_operator_agent_memory_app_updated ON operator_agent_memory (app_id, updated_at DESC);


-- ===== V53__operator_app_documents.sql =====
CREATE TABLE operator_app_documents (
    doc_id VARCHAR(64) PRIMARY KEY,
    app_id VARCHAR(128) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(128),
    description VARCHAR(512),
    content_text TEXT NOT NULL,
    byte_size BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_operator_app_documents_app ON operator_app_documents (app_id);


-- ===== V54__mimic_objects.sql =====
UPDATE object_nodes SET type = 'MIMICS' WHERE path = 'root.platform.mimics';

UPDATE object_nodes SET type = 'MIMIC' WHERE template_id = 'mimic-v1';


-- ===== V55__platform_user_time_zone.sql =====
ALTER TABLE platform_users
    ADD COLUMN time_zone VARCHAR(64) NOT NULL DEFAULT 'UTC';


-- ===== V56__variable_samples_observed_at.sql =====
-- ADR-0020: device measurement time (observed_at) vs platform ingest time (sampled_at).
ALTER TABLE variable_samples
    ADD COLUMN IF NOT EXISTS observed_at TIMESTAMP;

UPDATE variable_samples
SET observed_at = sampled_at
WHERE observed_at IS NULL;

ALTER TABLE variable_samples
    ALTER COLUMN observed_at SET NOT NULL;


-- ===== V57__alarm_shelves.sql =====
CREATE TABLE alarm_shelves (
    id VARCHAR(64) PRIMARY KEY,
    object_path VARCHAR(512) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    alert_rule_path VARCHAR(512),
    shelved_by VARCHAR(128) NOT NULL,
    shelved_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    comment VARCHAR(1024),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_alarm_shelves_active_lookup ON alarm_shelves (object_path, event_name, active);


-- ===== V58__platform_driver_locks.sql =====
CREATE TABLE platform_driver_locks (
    device_path VARCHAR(512) PRIMARY KEY,
    holder_id   VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_platform_driver_locks_expires ON platform_driver_locks (expires_at);


-- ===== V59__platform_cluster_replicas.sql =====
CREATE TABLE platform_cluster_replicas (
    replica_id         VARCHAR(64)  PRIMARY KEY,
    version            VARCHAR(32),
    environment        VARCHAR(64),
    java_version       VARCHAR(64),
    started_at         TIMESTAMP    NOT NULL,
    last_heartbeat_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_platform_cluster_replicas_heartbeat ON platform_cluster_replicas (last_heartbeat_at);


-- ===== V60__object_event_journal_flag.sql =====
ALTER TABLE object_nodes
    ADD COLUMN IF NOT EXISTS event_journal_enabled BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_object_nodes_event_journal_enabled
    ON object_nodes (event_journal_enabled);


-- ===== V61__model_to_blueprint.sql =====
-- Rename model domain to blueprint (ObjectType, catalog paths, persistence).

UPDATE object_nodes SET type = 'BLUEPRINT' WHERE type = 'MODEL';

UPDATE object_nodes SET path = REPLACE(path, 'relative-models', 'relative-blueprints');
UPDATE object_nodes SET path = REPLACE(path, 'absolute-models', 'absolute-blueprints');
UPDATE object_nodes SET path = REPLACE(path, 'root.platform.models', 'root.platform.blueprints');

ALTER TABLE object_nodes ADD COLUMN IF NOT EXISTS applied_blueprint_ids TEXT;
UPDATE object_nodes
SET applied_blueprint_ids = applied_model_ids
WHERE applied_model_ids IS NOT NULL
  AND (applied_blueprint_ids IS NULL OR TRIM(applied_blueprint_ids) = '');
ALTER TABLE object_nodes DROP COLUMN IF EXISTS applied_model_ids;

ALTER TABLE model_definitions RENAME TO blueprint_definitions;

UPDATE blueprint_definitions
SET definition_json = REPLACE(definition_json, '"modelVersion"', '"blueprintVersion"');


-- ===== V62__platform_jobs.sql =====
CREATE TABLE platform_jobs (
    job_id         UUID         PRIMARY KEY,
    job_type       VARCHAR(64)  NOT NULL,
    status         VARCHAR(32)  NOT NULL,
    priority       INT          NOT NULL DEFAULT 0,
    payload        VARCHAR(8192) NOT NULL,
    result         VARCHAR(1048576),
    error_message  VARCHAR(4096),
    holder_id      VARCHAR(64),
    expires_at     TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL,
    started_at     TIMESTAMP,
    completed_at   TIMESTAMP,
    created_by     VARCHAR(128)
);

CREATE INDEX idx_platform_jobs_status_created ON platform_jobs (status, created_at);
CREATE INDEX idx_platform_jobs_expires_at ON platform_jobs (expires_at);


-- ===== V63__platform_cluster_replica_role.sql =====
ALTER TABLE platform_cluster_replicas
    ADD COLUMN replica_role VARCHAR(16) NOT NULL DEFAULT 'all';


-- ===== V64__platform_cluster_replica_profile.sql =====
ALTER TABLE platform_cluster_replicas
    ADD COLUMN replica_profile VARCHAR(32) NOT NULL DEFAULT 'unified';

ALTER TABLE platform_cluster_replicas
    ADD COLUMN replica_capabilities VARCHAR(512) NOT NULL DEFAULT '';

UPDATE platform_cluster_replicas
SET replica_profile = CASE replica_role
    WHEN 'api' THEN 'edge-api'
    WHEN 'worker' THEN 'compute'
    WHEN 'all' THEN 'unified'
    ELSE replica_role
END
WHERE replica_profile = 'unified';


-- ===== V65__platform_cluster_replica_http_port.sql =====
ALTER TABLE platform_cluster_replicas
    ADD COLUMN http_port INT;

UPDATE platform_cluster_replicas
SET http_port = 8080
WHERE http_port IS NULL;


-- ===== V66__platform_binding_periodic_rules.sql =====
CREATE TABLE platform_binding_periodic_rules (
    object_path   VARCHAR(512) NOT NULL,
    rule_id       VARCHAR(128) NOT NULL,
    periodic_ms   BIGINT       NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    last_run_at   TIMESTAMP,
    next_run_at   TIMESTAMP  NOT NULL,
    PRIMARY KEY (object_path, rule_id)
);

CREATE INDEX idx_binding_periodic_next_run
    ON platform_binding_periodic_rules (next_run_at);


-- ===== V67__ai_tool_audit_metrics.sql =====
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS latency_ms BIGINT;
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS prompt_tokens INT;
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS completion_tokens INT;
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS turn_id VARCHAR(64);
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS step_no INT;
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS interaction_mode VARCHAR(16);
ALTER TABLE ai_tool_audit ADD COLUMN IF NOT EXISTS prompt_profile VARCHAR(32);

CREATE INDEX IF NOT EXISTS idx_ai_tool_audit_turn ON ai_tool_audit (app_id, turn_id, step_no);


-- ===== V68__agent_session_documents.sql =====
CREATE TABLE agent_session_documents (
    doc_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(128),
    description VARCHAR(512),
    content_text TEXT NOT NULL,
    byte_size BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_agent_session_documents_session
        FOREIGN KEY (session_id) REFERENCES agent_sessions(session_id) ON DELETE CASCADE
);

CREATE INDEX idx_agent_session_documents_session ON agent_session_documents (session_id);


-- ===== V69__dashboard_legacy_report_paths.sql =====
-- Rewrite legacy application-scoped report paths in dashboard layouts (pre tree-first V33).
UPDATE object_variables
SET value_json = regexp_replace(
        value_json,
        'root\.platform\.applications\.[^.]+\.reports\.',
        'root.platform.reports.',
        'g'
    )
WHERE name = 'layout'
  AND value_json LIKE '%root.platform.applications.%reports.%';


-- ===== V70__platform_tenant_quotas.sql =====
ALTER TABLE platform_tenants ADD COLUMN IF NOT EXISTS max_devices INT;
ALTER TABLE platform_tenants ADD COLUMN IF NOT EXISTS max_objects INT;


