{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ispf.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "ispf.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    ispf.io/bl: BL-186
type: Opaque
stringData:
  db-password: {{ default .Values.postgresql.auth.password .Values.secrets.dbPassword | quote }}
  db-username: {{ .Values.postgresql.auth.username | quote }}
  db-name: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
