-- Time-series samples for platform object variables (telemetry historian).
-- PostgreSQL: optional Timescale hypertable — SELECT create_hypertable('variable_samples', 'sampled_at', if_not_exists => TRUE);

CREATE TABLE IF NOT EXISTS variable_samples (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_path   VARCHAR(512) NOT NULL,
    variable_name VARCHAR(128) NOT NULL,
    field_name    VARCHAR(128) NOT NULL DEFAULT 'value',
    sampled_at    TIMESTAMP    NOT NULL,
    value_double  DOUBLE PRECISION,
    value_text    VARCHAR(2048)
);

CREATE INDEX IF NOT EXISTS idx_variable_samples_lookup
    ON variable_samples (object_path, variable_name, field_name, sampled_at DESC);

CREATE INDEX IF NOT EXISTS idx_variable_samples_retention
    ON variable_samples (sampled_at);
