CREATE TABLE IF NOT EXISTS object_nodes (
    id           VARCHAR(64)  PRIMARY KEY,
    path         VARCHAR(512) NOT NULL UNIQUE,
    type         VARCHAR(32)  NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    description  TEXT,
    template_id  VARCHAR(128),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    events_json  TEXT,
    functions_json TEXT
);

CREATE TABLE IF NOT EXISTS object_variables (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_path VARCHAR(512) NOT NULL,
    name         VARCHAR(128) NOT NULL,
    schema_json  TEXT         NOT NULL,
    value_json   TEXT,
    readable     BOOLEAN      NOT NULL DEFAULT TRUE,
    writable     BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMP,
    UNIQUE (object_path, name)
);

CREATE TABLE IF NOT EXISTS event_history (
    id           VARCHAR(64)  PRIMARY KEY,
    object_path VARCHAR(512) NOT NULL,
    event_name   VARCHAR(128) NOT NULL,
    level        VARCHAR(16)  NOT NULL,
    payload_json TEXT,
    occurred_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_history_object ON event_history(object_path, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_object_variables_path ON object_variables(object_path);
