CREATE TABLE ai_tool_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name VARCHAR(64) NOT NULL,
    app_id VARCHAR(128),
    actor VARCHAR(128),
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    provider_id VARCHAR(64),
    model_id VARCHAR(128),
    context_pack_version VARCHAR(64),
    errors_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_ai_tool_audit_created_at ON ai_tool_audit (created_at DESC);
CREATE INDEX idx_ai_tool_audit_app_id ON ai_tool_audit (app_id);
