CREATE TABLE IF NOT EXISTS event_correlators (
    id                 VARCHAR(64)  PRIMARY KEY,
    name               VARCHAR(256) NOT NULL,
    object_path       VARCHAR(512),
    event_name         VARCHAR(128) NOT NULL,
    window_seconds     INT          NOT NULL DEFAULT 0,
    min_occurrences    INT          NOT NULL DEFAULT 1,
    cooldown_seconds   INT          NOT NULL DEFAULT 60,
    action_type        VARCHAR(32)  NOT NULL,
    action_target      VARCHAR(512) NOT NULL,
    enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
    last_triggered_at  TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_correlators_match
    ON event_correlators(event_name, enabled);

CREATE TABLE IF NOT EXISTS correlator_hits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlator_id  VARCHAR(64)  NOT NULL,
    object_path   VARCHAR(512) NOT NULL,
    occurred_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_correlator_hits_window
    ON correlator_hits(correlator_id, occurred_at DESC);
