/** Excel / localized function names mapped to ISPF formula engine names. */
const FUNCTION_ALIASES: Record<string, string> = {
  СУММ: "SUM",
  СУММЕСЛИ: "SUMIF",
  СРЗНАЧ: "AVERAGE",
  СРЗНАЧЕСЛИ: "AVERAGEIF",
  СРЕДНЕЕ: "AVERAGE",
  МИН: "MIN",
  МАКС: "MAX",
  ЕСЛИ: "IF",
  ЕСЛИОШИБКА: "IFERROR",
  ОКРУГЛ: "ROUND",
  СЧЁТ: "COUNT",
  СЧЕТ: "COUNT",
  СЧЁТЕСЛИ: "COUNTIF",
  СЧЕТЕСЛИ: "COUNTIF",
  СЧЁТЗ: "COUNTA",
  СЧЕТЗ: "COUNTA",
  И: "AND",
  ИЛИ: "OR",
  НЕ: "NOT",
  ПРОСМОТР: "VLOOKUP",
  ГПР: "HLOOKUP",
  ИНДЕКС: "INDEX",
  ПОИСКПОЗ: "MATCH",
  ДЛСТР: "LEN",
  ЛЕВСИМВ: "LEFT",
  ПРАВСИМВ: "RIGHT",
  ПСТР: "MID",
  СЖПРОБЕЛЫ: "TRIM",
  ПРОПИСН: "UPPER",
  СТРОЧН: "LOWER",
  СЦЕПИТЬ: "CONCATENATE",
  СЕГОДНЯ: "TODAY",
  ТДАТА: "NOW",
  ГОД: "YEAR",
  МЕСЯЦ: "MONTH",
  ДЕНЬ: "DAY",
  ДАТА: "DATE",
  ДНЕЙ: "DAYS",
  ДЕНЬНЕД: "WEEKDAY",
  ЧАС: "HOUR",
  МИНУТЫ: "MINUTE",
  СЕКУНДЫ: "SECOND",
  ВРЕМЯ: "TIME",
  ДАТАМЕС: "EDATE",
  КОНМЕСЯЦА: "EOMONTH",
  РАЗНДАТ: "DATEDIF",
  СЛЧИС: "RAND",
  СЛУЧМЕЖДУ: "RANDBETWEEN",
  СУММЕСЛИМН: "SUMIFS",
  СЧЁТЕСЛИМН: "COUNTIFS",
  СЧЕТЕСЛИМН: "COUNTIFS",
  СРЗНАЧЕСЛИМН: "AVERAGEIFS",
  СУММПРОИЗВ: "SUMPRODUCT",
  ПРОМЕЖУТОЧИТОГИ: "SUBTOTAL",
  ЕСЛИМН: "IFS",
  ОБЪЕДИНИТЬ: "TEXTJOIN",
  СМЕЩ: "XLOOKUP",
  ЧИСЛРАБДН: "NETWORKDAYS",
  РАБДЕНЬ: "WORKDAY",
  ОКРУГЛВВЕРХ: "ROUNDUP",
  ОКРУГЛВНИЗ: "ROUNDDOWN",
  МЕДИАНА: "MEDIAN",
  СТАНДОТКЛОН: "STDEV.S",
  STDEV: "STDEV.S",
  LN: "LN",
  EXP: "EXP",
  LOG: "LOG",
  LOG10: "LOG10",
  ПИ: "PI",
  ЗНАК: "SIGN",
  ОТБР: "TRUNC",
  ОКРУГЛТ: "MROUND",
  НАЙТИ: "FIND",
  ПОИСК: "SEARCH",
  ПОДСТАВИТЬ: "SUBSTITUTE",
  ЗАМЕНИТЬ: "REPLACE",
  ЗНАЧЕН: "VALUE",
  СОВПАД: "EXACT",
  ДАТАЗНАЧ: "DATEVALUE",
  ВРЕМЗНАЧ: "TIMEVALUE",
  НОМНЕД: "WEEKNUM",
  ДОЛЯГОДА: "YEARFRAC",
  ЕСЛИНД: "IFNA",
  ВЫБОР: "CHOOSE",
  ДИСП: "VAR.S",
  ДИСПР: "VAR",
  ПЕРСЕНТИЛЬ: "PERCENTILE",
  КВАРТИЛЬ: "QUARTILE",
  НАИБОЛЬШИЙ: "LARGE",
  НАИМЕНЬШИЙ: "SMALL",
  РАНГ: "RANK",
  ЧПС: "NPV",
  ПЛТ: "PMT",
  БС: "FV",
  ПС: "PV",
  КПЕР: "NPER",
  СТАВКА: "RATE",
  ВСД: "IRR",
  СТРОКА: "ROW",
  СТОЛБЕЦ: "COLUMN",
  ЧИСЛСТР: "ROWS",
  ЧИСЛСТОЛБ: "COLUMNS",
  ЕНД: "ISNA",
  ЕОШ: "ISERR",
  SIN: "SIN",
  COS: "COS",
  TAN: "TAN",
  ASIN: "ASIN",
  ACOS: "ACOS",
  ATAN: "ATAN",
  ATAN2: "ATAN2",
  РАДИАН: "RADIANS",
  ГРАДУСЫ: "DEGREES",
  ОСТАТ: "MOD",
  СТЕПЕНЬ: "POWER",
  КОРЕНЬ: "SQRT",
  ЦЕЛОЕ: "INT",
  ОКРВВЕРХ: "CEILING",
  ОКРВНИЗ: "FLOOR",
  AVG: "AVERAGE",
};

export const SUPPORTED_SHEET_FUNCTIONS = new Set([
  "SUM",
  "AVERAGE",
  "AVG",
  "MIN",
  "MAX",
  "COUNT",
  "COUNTA",
  "COUNTBLANK",
  "IF",
  "IFERROR",
  "ROUND",
  "ABS",
  "AND",
  "OR",
  "NOT",
  "PRODUCT",
  "MOD",
  "POWER",
  "SQRT",
  "INT",
  "CEILING",
  "FLOOR",
  "VLOOKUP",
  "HLOOKUP",
  "INDEX",
  "MATCH",
  "SUMIF",
  "COUNTIF",
  "AVERAGEIF",
  "SUMIFS",
  "COUNTIFS",
  "AVERAGEIFS",
  "SUMPRODUCT",
  "SUBTOTAL",
  "IFS",
  "TEXTJOIN",
  "XLOOKUP",
  "NETWORKDAYS",
  "WORKDAY",
  "ROUNDUP",
  "ROUNDDOWN",
  "MEDIAN",
  "STDEV",
  "STDEV.S",
  "LOG",
  "LN",
  "LOG10",
  "EXP",
  "PI",
  "SIGN",
  "TRUNC",
  "MROUND",
  "FIND",
  "SEARCH",
  "SUBSTITUTE",
  "REPLACE",
  "VALUE",
  "EXACT",
  "DATEVALUE",
  "TIMEVALUE",
  "WEEKNUM",
  "YEARFRAC",
  "SWITCH",
  "CHOOSE",
  "IFNA",
  "VAR",
  "VAR.S",
  "VARS",
  "VAR.P",
  "VARP",
  "PERCENTILE",
  "QUARTILE",
  "LARGE",
  "SMALL",
  "RANK",
  "NPV",
  "IRR",
  "PMT",
  "FV",
  "PV",
  "NPER",
  "RATE",
  "SIN",
  "COS",
  "TAN",
  "ASIN",
  "ACOS",
  "ATAN",
  "ATAN2",
  "RADIANS",
  "DEGREES",
  "ISNA",
  "ISERR",
  "ROW",
  "COLUMN",
  "ROWS",
  "COLUMNS",
  "LEN",
  "LEFT",
  "RIGHT",
  "MID",
  "TRIM",
  "UPPER",
  "LOWER",
  "CONCAT",
  "CONCATENATE",
  "TEXT",
  "TODAY",
  "NOW",
  "YEAR",
  "MONTH",
  "DAY",
  "DATE",
  "DAYS",
  "WEEKDAY",
  "HOUR",
  "MINUTE",
  "SECOND",
  "TIME",
  "EDATE",
  "EOMONTH",
  "DATEDIF",
  "RAND",
  "RANDBETWEEN",
  "ISBLANK",
  "ISNUMBER",
  "ISTEXT",
  "ISERROR",
  "ISPREF",
  "ISPSUM",
  "ISPHIST",
]);

export function normalizeFunctionName(name: string): string {
  const upper = name.toUpperCase();
  return FUNCTION_ALIASES[upper] ?? upper;
}

/** Strip Excel absolute refs ($A$1 → A1) and normalize list separators. */
export function normalizeFormulaSyntax(formula: string): string {
  return formula.replace(/\$/g, "").replace(/;/g, ",");
}

/** Replace localized function names with English equivalents (case-insensitive). */
export function normalizeExcelFunctionNames(formula: string): string {
  return formula.replace(
    /([A-Za-zА-ЯЁа-яё][A-Za-z0-9_.А-ЯЁа-яё]*)\s*(?=\()/g,
    (match) => normalizeFunctionName(match)
  );
}

export function normalizeImportedFormula(rawFormula: string): string {
  const body = rawFormula.trim().startsWith("=") ? rawFormula.trim().slice(1) : rawFormula.trim();
  return normalizeExcelFunctionNames(normalizeFormulaSyntax(body));
}

export function extractFormulaFunctionNames(formula: string): string[] {
  const names = new Set<string>();
  const re = /([A-Za-zА-ЯЁа-яё][A-Za-z0-9_.А-ЯЁа-яё]*)\s*(?=\()/g;
  let match: RegExpExecArray | null;
  while ((match = re.exec(formula)) !== null) {
    names.add(normalizeFunctionName(match[1]));
  }
  return [...names];
}

export function findUnsupportedFunctions(formula: string): string[] {
  return extractFormulaFunctionNames(formula).filter((name) => !SUPPORTED_SHEET_FUNCTIONS.has(name));
}
