plugins {
    id("org.springframework.boot")
    id("io.spring.dependency-management")
}

dependencies {
    implementation(project(":packages:ispf-core"))
    implementation(project(":packages:ispf-expression"))
    implementation(project(":packages:ispf-driver-api"))
    implementation(project(":packages:ispf-driver-mqtt"))
    implementation(project(":packages:ispf-driver-modbus"))
    implementation(project(":packages:ispf-driver-modbus-rtu"))
    implementation(project(":packages:ispf-driver-modbus-udp"))
    implementation(project(":packages:ispf-driver-snmp"))
    implementation(project(":packages:ispf-driver-virtual"))
    implementation(project(":packages:ispf-driver-http"))
    implementation(project(":packages:ispf-driver-icmp"))
    implementation(project(":packages:ispf-driver-ssh"))
    implementation(project(":packages:ispf-driver-coap"))
    implementation(project(":packages:ispf-driver-opcua"))
    implementation(project(":packages:ispf-driver-opcua-server"))
    implementation(project(":packages:ispf-driver-s7"))
    implementation(project(":packages:ispf-driver-iec104"))
    implementation(project(":packages:ispf-driver-iec104-server"))
    implementation(project(":packages:ispf-driver-bacnet"))
    implementation(project(":packages:ispf-driver-dnp3"))
    implementation(project(":packages:ispf-driver-jmx"))
    implementation(project(":packages:ispf-driver-jdbc"))
    implementation(project(":packages:ispf-driver-file"))
    implementation(project(":packages:ispf-driver-folder"))
    implementation(project(":packages:ispf-driver-application"))
    implementation(project(":packages:ispf-driver-message-stream"))
    implementation(project(":packages:ispf-driver-nmea"))
    implementation(project(":packages:ispf-driver-telnet"))
    implementation(project(":packages:ispf-driver-soap"))
    implementation(project(":packages:ispf-driver-ip-host"))
    implementation(project(":packages:ispf-driver-kafka"))
    implementation(project(":packages:ispf-driver-gps-tracker"))
    implementation(project(":packages:ispf-driver-flexible"))
    implementation(project(":packages:ispf-driver-mbus"))
    implementation(project(":packages:ispf-driver-dlms"))
    implementation(project(":packages:ispf-driver-ethernet-ip"))
    implementation(project(":packages:ispf-driver-omron-fins"))
    implementation(project(":packages:ispf-driver-asterisk"))
    implementation(project(":packages:ispf-driver-smpp"))
    implementation(project(":packages:ispf-driver-smb"))
    implementation(project(":packages:ispf-driver-modem-at"))
    implementation(project(":packages:ispf-driver-sip"))
    implementation(project(":packages:ispf-driver-xmpp"))
    implementation(project(":packages:ispf-driver-corba"))
    implementation(project(":packages:ispf-driver-opc-da"))
    implementation(project(":packages:ispf-driver-opc-bridge"))
    implementation(project(":packages:ispf-driver-odbc"))
    implementation(project(":packages:ispf-driver-jms"))
    implementation(project(":packages:ispf-driver-cwmp"))
    implementation(project(":packages:ispf-driver-web-transaction"))
    implementation(project(":packages:ispf-driver-http-server"))
    implementation(project(":packages:ispf-driver-graph-db"))
    implementation(project(":packages:ispf-driver-vmware"))
    implementation(project(":packages:ispf-driver-smis"))
    implementation(project(":packages:ispf-driver-ldap"))
    implementation(project(":packages:ispf-driver-dhcp"))
    implementation(project(":packages:ispf-driver-imap"))
    implementation(project(":packages:ispf-driver-pop3"))
    implementation(project(":packages:ispf-driver-radius"))
    implementation(project(":packages:ispf-driver-ipmi"))
    implementation(project(":packages:ispf-driver-wmi"))
    implementation(project(":packages:ispf-plugin-model"))
    implementation(project(":packages:ispf-plugin-workflow"))
    implementation(project(":packages:ispf-ai-api"))
    implementation(project(":packages:ispf-ai-openai-compatible"))
    implementation(project(":packages:ispf-ai-ollama"))

    implementation("io.nats:jnats:2.20.5")

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-security-oauth2-resource-server")

    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("com.h2database:h2")
    implementation("org.springframework.boot:spring-boot-starter-flyway")
    runtimeOnly("org.flywaydb:flyway-database-postgresql")

    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.micrometer:micrometer-registry-otlp")

    implementation("com.haulmont.yarg:yarg:2.2.22") {
        exclude(group = "javax.xml.bind", module = "jaxb-api")
    }
    // YARG XlsxFormatter uses docx4j; JDK 11+ removed internal JAXB — required for .xlsx templates
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    implementation("org.glassfish.jaxb:jaxb-runtime:2.3.9")
    implementation("org.docx4j:docx4j-JAXB-ReferenceImpl:8.3.11")

    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
    testImplementation("org.springframework.boot:spring-boot-starter-security-test")
    testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")
    testImplementation("org.mockito:mockito-core")
    testRuntimeOnly("com.h2database:h2")
}

tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    archiveBaseName.set("ispf-server")
    from(rootProject.file("LICENSE")) { into("META-INF") }
    from(rootProject.file("NOTICE")) { into("META-INF") }
}

springBoot {
    buildInfo()
}
