"""Flexibase customer event code catalog (P_I_IV_1.10_227, BM_Pouch_final).

Parsed one-off from downtime_event_code_dict_customer.sql (155 codes, OGP/BM/POUCH/MES)
and downtime_setup_tag_dict_zp.sql (16 Zero Pull tags) - reference data, do not edit by hand.
Mapping to ISA-95 core columns is applied at parse time (see generate_bundle.py).
"""

# (code, event_class, name, requires_length, requires_time, requires_comment,
#  oee_bucket, six_big_loss, sort_order, catalog, section, operator_hint, time_type)
EVENT_CODES = [
    ('OGP-101', 'PRODUCTION', 'Производство: Чистый процесс печать', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 101, 'OGP', 'Printing', 'Только процесс печати', 'Tr'),
    ('OGP-102', 'PRODUCTION', 'Производство: Чистый процесс ламинация', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 102, 'OGP', 'Lamination', 'Только процесс ламинации', 'Tr'),
    ('OGP-103', 'PRODUCTION', 'Производство: Чистый процесс резка', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 103, 'OGP', 'Slitting', 'Только процесс резки', 'Tr'),
    ('OGP-104', 'PRODUCTION', 'Производство: Чистый процесс перемотка', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 104, 'OGP', 'Slitting', 'Только процесс перемотки', 'Tr'),
    ('OGP-105', 'PRODUCTION', 'Производство: Чистый процесс нанесение ЧЗ', True, True, True, 'PERFORMANCE', 'REDUCED_SPEED', 105, 'OGP', 'Slitting', 'Только процесс нанесение честного знака', 'Tr'),
    ('OGP-110', 'DOWNTIME', 'Производство: Потери скорости', False, False, True, 'PERFORMANCE', 'REDUCED_SPEED', 110, 'OGP', 'All', 'Все причины, которые снижают ФАКТИЧЕСКУЮ скорость оборудования заносятся на этот код', 'Tl'),
    ('OGP-113', 'DOWNTIME', 'Плановый простой: Плановое отсутствие загрузки или выходной', False, False, False, 'NONE', None, 113, 'OGP', 'All', 'Заносится Плановым отделом', 'Tn'),
    ('OGP-114', 'DOWNTIME', 'Плановый простой: Отсутствие полуфабриката с предыдущей стадии для Резки и Перемотки', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 114, 'OGP', 'Slitting', 'Только для участка резки', 'Td'),
    ('OGP-115', 'DOWNTIME', 'Нестандартная операция: Подрезка материала нестандартной ширины', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 115, 'OGP', 'Slitting', 'Все время подрезки на этот код', 'Td'),
    ('OGP-116', 'DOWNTIME', 'Нестандартная операция: Подрезка печатного материала Royal Canin', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 116, 'OGP', 'Slitting', 'Все время подрезки на этот код', 'Td'),
    ('OGP-117', 'DOWNTIME', 'Плановое техническое обслуживание', False, True, True, 'NONE', None, 117, 'OGP', 'All', 'ФАКТИЧЕСКОЕ время ТО', 'Tp'),
    ('OGP-119', 'DOWNTIME', 'Стандартная операция: Штатная остановка оборудования', False, True, True, 'AVAILABILITY', 'PLANNED_STOP', 119, 'OGP', 'All', 'Указать причины ШТАТНОЙ остановки', 'Td'),
    ('OGP-120', 'SETUP', 'Настройка: Механическая', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 120, 'OGP', 'All', 'Только настройка оборудования на заказ', 'Ts'),
    ('OGP-121', 'SETUP', 'Настройка: Технологическая', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 121, 'OGP', 'Printing', 'Только для участка печати; Указать причины корректировки, наименование краски, № секции', 'Ts'),
    ('OGP-125', 'DOWNTIME', 'Ожидание: Отсутствие сырьевых материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 125, 'OGP', 'All', 'Указать наименование материала, причину отсутствия', 'Td'),
    ('OGP-126', 'DOWNTIME', 'Ожидание: Отсутствие краски или клея', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 126, 'OGP', 'Printing / Lamination', 'Только для участка печати и ламинации; Указать наименование краски/клея, причину отсутствия', 'Td'),
    ('OGP-127', 'DOWNTIME', 'Ожидание: Отсутствие цилиндров или каламажей; поломка вспомогательного оборудования (помпа, фильтр, брызговик и т.д)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 127, 'OGP', 'Printing / Lamination', 'Только для участка печати и ламинации; Указать наименование оборудования, причину отсутствия/поломки', 'Td'),
    ('OGP-128', 'DOWNTIME', 'Ожидание: Отсутствие прессёров', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 128, 'OGP', 'Printing / Lamination', 'Указать номер прессера/ов, ширину прессера/ов, причину отсутствия', 'Td'),
    ('OGP-129', 'DOWNTIME', 'Ожидание: Отсутствие расходных материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 129, 'OGP', 'All', 'Указать наименование материала/ов, причину отсутствия', 'Td'),
    ('OGP-130', 'DOWNTIME', 'Ожидание: Отсутствие полуфабриката с предыдущей стадии', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 130, 'OGP', 'Lamination / Slitting', 'Указать наименование полуфабриката, причину отсутствия', 'Td'),
    ('OGP-131', 'DOWNTIME', 'Ожидание: Отсутствие документации', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 131, 'OGP', 'All', 'Указать вид документации', 'Td'),
    ('OGP-132', 'DOWNTIME', 'Стандартная операция: Запуск после штатной остановки оборудования', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 132, 'OGP', 'All', 'Заносится время запуска (чистки) ДО настройки оборудования', 'Td'),
    ('OGP-133', 'DOWNTIME', 'Эффективная остановка', False, True, True, 'AVAILABILITY', 'PLANNED_STOP', 133, 'OGP', 'All', 'Заносится время ежесменной уборки оборудования', 'Td'),
    ('OGP-134', 'DOWNTIME', 'Чистка: Устранение розлива', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 134, 'OGP', 'Printing / Lamination', 'Указать причину и место розлива', 'Td'),
    ('OGP-135', 'DOWNTIME', 'Проблемы с входящим материалом: Несоответствующий материал', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 135, 'OGP', 'Printing / Lamination', 'Указать наименование материала, описание проблемы', 'Td'),
    ('OGP-136', 'DOWNTIME', 'Печатный цилиндр: Повреждение цилиндра или замена по износу', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 136, 'OGP', 'Printing / Lamination', 'Указать № цилиндра, причину и вид повреждения/износа, вид повреждения износа', 'Td'),
    ('OGP-137', 'QUALITY', 'Печатный дефект: Приводка печати', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 137, 'OGP', 'Printing', 'Указать местоположение неприводки печати, причину, коррегирующие действия', 'Td'),
    ('OGP-138', 'QUALITY', 'Печатный дефект: Шаг печати (cut-off)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 138, 'OGP', 'Printing', 'Указать фактический шаг печати и целевое значение шага печати, коррегирующие действия', 'Td'),
    ('OGP-139', 'QUALITY', 'Печатный дефект: Ракельные полосы', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 139, 'OGP', 'Printing', 'Указать местоположение, причину, коррегирующие действия, номер ракеля', 'Td'),
    ('OGP-140', 'QUALITY', 'Печатный дефект: Истекание краски', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 140, 'OGP', 'Printing', 'Указать местоположение, причину, коррегирующие действия, номер ракеля', 'Td'),
    ('OGP-141', 'QUALITY', 'Печатный дефект: Брызги краски', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 141, 'OGP', 'Printing', 'Указать местоположение, причину, коррегирующие действия', 'Td'),
    ('OGP-142', 'QUALITY', 'Печатный дефект: Непропечатка цвета', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 142, 'OGP', 'Printing', 'Указать цвет, причину, коррегирующие действия, местоположение', 'Td'),
    ('OGP-143', 'QUALITY', 'Печатный дефект: Отклонение цвета', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 143, 'OGP', 'Printing', 'Указать цвет, причину, коррегирующие действия, местоположение', 'Td'),
    ('OGP-144', 'QUALITY', 'Печатный дефект: Тонирование', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 144, 'OGP', 'Printing', 'Указать местоположение, причину, коррегирующие действия, номер ракеля', 'Td'),
    ('OGP-145', 'QUALITY', 'Печатный дефект: Засыхание', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 145, 'OGP', 'Printing', 'Указать местоположение, причину, коррегирующие действия', 'Td'),
    ('OGP-146', 'QUALITY', 'Печатный дефект: Молнии', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 146, 'OGP', 'Printing', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-147', 'QUALITY', 'Печатный дефект: Дефект промо-кода', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 147, 'OGP', 'Printing', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-148', 'QUALITY', 'Печатный дефект: Прочий печатный дефект', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 148, 'OGP', 'Printing', 'Указать причину (например - складки, смещение материала, наличие более 2ух дефектов, проблемы с CS), коррегирующие действия', 'Td'),
    ('OGP-149', 'QUALITY', 'Ламинационный дефект: Непропечатка клея', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 149, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-150', 'QUALITY', 'Ламинационный дефект: Складки', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 150, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия, местоположение', 'Td'),
    ('OGP-151', 'QUALITY', 'Ламинационный дефект: Блистеринг', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 151, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-152', 'QUALITY', 'Ламинационный дефект: Волны на материале', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 152, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-153', 'QUALITY', 'Ламинационный дефект: Гель на пропилене', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 153, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-154', 'QUALITY', 'Ламинационный дефект: Дефект или смещение скретчинга', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 154, 'OGP', 'Lamination', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-155', 'QUALITY', 'Ламинационный дефект: Прочий ламинационный дефект', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 155, 'OGP', 'Lamination', 'Указать причину (например - смещение материала, наличие более 2ух дефектов), коррегирующие действия', 'Td'),
    ('OGP-156', 'QUALITY', 'Дефект резки: Телескоп', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 156, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-157', 'QUALITY', 'Дефект резки: Складки', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 157, 'OGP', 'Slitting', 'Указать причину, расположение дефекта, коррегирующие действия', 'Td'),
    ('OGP-158', 'QUALITY', 'Дефект резки: Неудалённый трим', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 158, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-159', 'QUALITY', 'Дефект резки: Смещение резки', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 159, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-160', 'QUALITY', 'Дефект резки: Перетянутый материал на бобине', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 160, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-161', 'QUALITY', 'Дефект резки: Смещение гильзы', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 161, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-162', 'QUALITY', 'Дефект резки: Прочий дефект резки', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 162, 'OGP', 'Slitting', 'Указать причину (например - наличие более 2ух дефектов), коррегирующие действия', 'Td'),
    ('OGP-163', 'QUALITY', 'Дефект лазер-скоринга: Дефект лазер-скоринга', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 163, 'OGP', 'Slitting', 'Указать причину, коррегирующие действия', 'Td'),
    ('OGP-164', 'DOWNTIME', 'Обрыв материала: Обрыв материала', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 164, 'OGP', 'All', 'Указать причину, местоположение, ФИО того, кто делал склейку', 'Td'),
    ('OGP-165', 'DOWNTIME', 'Нестандартная операция: Сортировка', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 165, 'OGP', 'Slitting', 'Указать № NCR/заказа, по которому выполнялась сортировка', 'Td'),
    ('OGP-166', 'DOWNTIME', 'Недоукомплектованная смена: Отсутствие человека', False, False, True, 'AVAILABILITY', 'UNPLANNED_STOP', 166, 'OGP', 'All', 'Указать отсутствие сотрудника (например - работа без помощника), причина', 'Td'),
    ('OGP-167', 'DOWNTIME', 'Сбой IT систем : Сбой IT систем', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 167, 'OGP', 'All', 'Указать наименование системы, которая не работает, коррегирующие действия', 'Td'),
    ('OGP-168', 'DOWNTIME', 'Плановый простой: Плановое время собрания', False, True, True, 'NONE', None, 168, 'OGP', 'All', 'Только по распоряжению руководителя', 'Td'),
    ('OGP-169', 'DOWNTIME', 'Плановый простой: Плановое время обучения', False, False, True, 'NONE', None, 169, 'OGP', 'All', 'Обучение нового сотрудника (адаптация)', 'Td'),
    ('OGP-170', 'DOWNTIME', 'Внеплановый простой: Превышение планового времени', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 170, 'OGP', 'All', 'Указать причину ВНЕПЛАНОВОГО простоя', 'Td'),
    ('OGP-171', 'DOWNTIME', 'Ожидание: Температура в производственном цехе не соответствует спецификации', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 171, 'OGP', 'All', 'Указать причину', 'Td'),
    ('OGP-172', 'DOWNTIME', 'Ожидание: Влажность в производственном цехе не соответствует спецификации', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 172, 'OGP', 'All', 'Указать причину', 'Td'),
    ('OGP-173', 'DOWNTIME', 'Ожидание: замена рулона, склейка', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 173, 'OGP', 'All', 'Только для LM210. Указать время и написать комментарии', 'Td'),
    ('MES-174', 'DOWNTIME', 'Склейка рулона (MES post-commit)', True, False, False, 'AVAILABILITY', 'UNPLANNED_STOP', 174, 'MES', 'All', 'Post-commit traceability; CL-DT-04', 'Td'),
    ('OGP-175', 'DOWNTIME', 'Авария электроники: Авария электроники', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 175, 'OGP', 'All', 'Указать наименование системы, которая не работает, коррегирующие действия', 'Tb'),
    ('BM-201', 'PRODUCTION', 'Производство: Чистый процесс выпуска ГП', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 201, 'BM', 'Packaging', 'Только процесс производства продукции', 'Tr'),
    ('BM-202', 'SETUP', 'Переход/перенастройка оборудования', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 202, 'BM', 'Packaging', 'Только настройка оборудования на заказ', 'Ts'),
    ('BM-203', 'DOWNTIME', 'Эффективная остановка', False, True, True, 'AVAILABILITY', 'PLANNED_STOP', 203, 'BM', 'Packaging', 'Заносится время ежесменной уборки оборудования', 'Td'),
    ('BM-204', 'SETUP', 'Настройка Честного знака', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 204, 'BM', 'Packaging', 'Только процесс настройки честного знака', 'Ts'),
    ('BM-205', 'DOWNTIME', 'Плановое обслуживание оборудования', True, True, False, 'NONE', None, 205, 'BM', 'Packaging', '-', 'Tn'),
    ('BM-206', 'DOWNTIME', 'Плановый простой: Плановое отсутствие загрузки или выходной', False, True, False, 'NONE', None, 206, 'BM', 'Packaging', '-', 'Tn'),
    ('BM-207', 'DOWNTIME', 'Плановый простой: Ожидание полуфабриката с предыдущей стадии', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 207, 'BM', 'Packaging', 'Указать наименование полуфабриката, причину отсутствия', 'Td'),
    ('BM-208', 'DOWNTIME', 'Плановый простой: Плановое время собрания (обучения)', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 208, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-209', 'SETUP', 'Тесты: Технология (поломки отдельным кодом, настройка и run внутри кода)', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 209, 'BM', 'Packaging', '-', 'Ts'),
    ('BM-210', 'DOWNTIME', 'Авария электроники: Авария электроники', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 210, 'BM', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Tb'),
    ('BM-211', 'DOWNTIME', 'Авария механики: Авария механики', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 211, 'BM', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Tb'),
    ('BM-212', 'DOWNTIME', 'Поломка вспомогательного оборудования', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 212, 'BM', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Td'),
    ('BM-213', 'DOWNTIME', 'Отсутствие энергоресурсов: Отсутствие энергоресурсов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 213, 'BM', 'Packaging', 'В случае отключения электроэнергии', 'Td'),
    ('BM-214', 'DOWNTIME', 'Сбой IT систем', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 214, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-215', 'DOWNTIME', 'Отсутствие расходных материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 215, 'BM', 'Packaging', 'Указать наименование материала/ов, причину отсутствия', 'Td'),
    ('BM-216', 'DOWNTIME', 'Внеплановый простой: Отсутствие сырьевых материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 216, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-217', 'DOWNTIME', 'Недостаточное качество входящего полуфабриката', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 217, 'BM', 'Packaging', 'Указать дефект, наименование полуфабриката', 'Td'),
    ('BM-218', 'DOWNTIME', 'Внеплановый простой: Закрытие предыдущего заказа', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 218, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-219', 'DOWNTIME', 'Сортировка готовой продукции', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 219, 'BM', 'Packaging', 'Указать № NCR/заказа, по которому выполнялась сортировка', 'Td'),
    ('BM-220', 'DOWNTIME', 'Недоукомплектованная смена: Работа одного оператора', False, True, False, 'AVAILABILITY', 'UNPLANNED_STOP', 220, 'BM', 'Packaging', '-', 'Td'),
    ('BM-221', 'DOWNTIME', 'Ожидание: Температура в производственном цехе не соответствует спецификации', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 221, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-222', 'SETUP', 'Настройка: нагрев машины/запуск после ремонта (ТО)', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 222, 'BM', 'Packaging', '-', 'Ts'),
    ('BM-223', 'DOWNTIME', 'Обрыв материала: Струна', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 223, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-224', 'DOWNTIME', 'Замятие/Обрыв материала', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 224, 'BM', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('BM-225', 'DOWNTIME', 'Замена лезвий', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 225, 'BM', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('BM-226', 'SETUP', 'Настройка/Замена/Чистка вырубных устройств', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 226, 'BM', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('BM-227', 'DOWNTIME', 'Чистка/замена расходных материалов (силикон,тефлон)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 227, 'BM', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('BM-228', 'DOWNTIME', 'Чистка элементов машины', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 228, 'BM', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('BM-229', 'DOWNTIME', 'Протечка', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 229, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-230', 'DOWNTIME', 'Низкая прочность шва', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 230, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-231', 'DOWNTIME', 'Нарушение геометрии пакета', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 231, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-232', 'DOWNTIME', 'Проблемы с ZIP', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 232, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-233', 'DOWNTIME', 'Складки/волны на материале', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 233, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-234', 'DOWNTIME', 'Пузыри воздуха', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 234, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-235', 'DOWNTIME', 'Завальцовка', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 235, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-236', 'DOWNTIME', 'Дефекты принтера кода', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 236, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-237', 'DOWNTIME', 'Смещение материала в машине (некорректная подача)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 237, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-238', 'DOWNTIME', 'Прожиги материала', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 238, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('BM-239', 'SETUP', 'Настройка датчиков (LPC, Cut-off, склейка и др.)', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 239, 'BM', 'Packaging', 'Указать датчик, причину, местоположение', 'Ts'),
    ('BM-240', 'SETUP', 'Настройка сварных панелей', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 240, 'BM', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('BM-241', 'SETUP', 'Настройка тянущих валов', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 241, 'BM', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('BM-242', 'DOWNTIME', 'Установка/снятие рулона с полуфабрикатом в машину', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 242, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-243', 'DOWNTIME', 'Регулировка узла формирования квадратного дна', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 243, 'BM', 'Packaging', 'Указать причину', 'Td'),
    ('BM-244', 'DOWNTIME', 'Царапины на гассете/F&B', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 244, 'BM', 'Packaging', 'Указать местоположение, причину, действия', 'Td'),
    ('POUCH-301', 'PRODUCTION', 'Чистый процесс производства паучей', True, True, False, 'PERFORMANCE', 'REDUCED_SPEED', 301, 'POUCH', 'Packaging', 'Только процесс производства продукции', 'Tr'),
    ('POUCH-302', 'SETUP', 'Переход/перенастройка оборудования', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 302, 'POUCH', 'Packaging', 'Только настройка оборудования на заказ', 'Ts'),
    ('POUCH-303', 'DOWNTIME', 'Эффективная остановка', False, True, True, 'AVAILABILITY', 'PLANNED_STOP', 303, 'POUCH', 'Packaging', 'Заносится время ежесменной уборки оборудования', 'Td'),
    ('POUCH-304', 'SETUP', 'Настройка Честного знака', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 304, 'POUCH', 'Packaging', 'Только процесс настройки честного знака', 'Ts'),
    ('POUCH-305', 'DOWNTIME', 'Плановое обслуживание оборудования', True, True, False, 'NONE', None, 305, 'POUCH', 'Packaging', '-', 'Tn'),
    ('POUCH-306', 'DOWNTIME', 'Плановый простой: Плановое отсутствие загрузки или выходной', False, True, False, 'NONE', None, 306, 'POUCH', 'Packaging', '-', 'Tn'),
    ('POUCH-307', 'DOWNTIME', 'Плановый простой: Ожидание полуфабриката с предыдущей стадии', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 307, 'POUCH', 'Packaging', 'Указать наименование полуфабриката, причину отсутствия', 'Td'),
    ('POUCH-308', 'DOWNTIME', 'Плановый простой: Плановое время собрания (обучения)', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 308, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-309', 'SETUP', 'Тесты: Технология (поломки отдельным кодом, настройка и run внутри кода)', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 309, 'POUCH', 'Packaging', '-', 'Ts'),
    ('POUCH-310', 'DOWNTIME', 'Авария электроники: Авария электроники', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 310, 'POUCH', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Tb'),
    ('POUCH-311', 'DOWNTIME', 'Авария механики: Авария механики', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 311, 'POUCH', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Tb'),
    ('POUCH-312', 'DOWNTIME', 'Поломка вспомогательного оборудования', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 312, 'POUCH', 'Packaging', 'Указать наименование системы, которая не работает, действия', 'Td'),
    ('POUCH-313', 'DOWNTIME', 'Отсутствие энергоресурсов: Отсутствие энергоресурсов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 313, 'POUCH', 'Packaging', 'В случае отключения электроэнергии', 'Td'),
    ('POUCH-314', 'DOWNTIME', 'Сбой IT систем', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 314, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-315', 'DOWNTIME', 'Отсутствие расходных материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 315, 'POUCH', 'Packaging', 'Указать наименование материала/ов, причину отсутствия', 'Td'),
    ('POUCH-316', 'DOWNTIME', 'Внеплановый простой: Отсутствие сырьевых материалов', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 316, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-317', 'DOWNTIME', 'Недостаточное качество входящего полуфабриката', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 317, 'POUCH', 'Packaging', 'Указать дефект, наименование полуфабриката', 'Td'),
    ('POUCH-318', 'DOWNTIME', 'Внеплановый простой: Закрытие предыдущего заказа', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 318, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-319', 'DOWNTIME', 'Сортировка готовой продукции', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 319, 'POUCH', 'Packaging', 'Указать № NCR/заказа, по которому выполнялась сортировка', 'Td'),
    ('POUCH-320', 'DOWNTIME', 'Недоукомплектованная смена: Работа одного оператора', False, True, False, 'AVAILABILITY', 'UNPLANNED_STOP', 320, 'POUCH', 'Packaging', '-', 'Td'),
    ('POUCH-321', 'DOWNTIME', 'Ожидание: Температура в производственном цехе не соответствует спецификации', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 321, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-322', 'SETUP', 'Настройка: нагрев машины/запуск после ремонта (ТО)', True, True, False, 'AVAILABILITY', 'PLANNED_STOP', 322, 'POUCH', 'Packaging', '-', 'Ts'),
    ('POUCH-323', 'DOWNTIME', 'Обрыв донной ленты', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 323, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-324', 'DOWNTIME', 'Остановка Стекер/Конвейер', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 324, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-325', 'DOWNTIME', 'Обрыв основного материала', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 325, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-326', 'DOWNTIME', 'Замена/Углубление/Переворот лезвий', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 326, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-327', 'SETUP', 'Настройка/Замена вырубных устройств', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 327, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('POUCH-328', 'DOWNTIME', 'Поворот/Замена расходных материалов (силикон,тефлон)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 328, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-329', 'DOWNTIME', 'Чистка элементов машины', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 329, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-330', 'DOWNTIME', 'Протечка', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 330, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-331', 'DOWNTIME', 'Низкая прочность шва', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 331, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-332', 'DOWNTIME', 'Складки/волны на материале', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 332, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-333', 'DOWNTIME', 'Пузыри воздуха', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 333, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-334', 'DOWNTIME', 'Завальцовка', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 334, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-335', 'DOWNTIME', 'Смещение материала в машине', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 335, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-336', 'DOWNTIME', 'Слипание', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 336, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-337', 'DOWNTIME', 'Прожиги материала', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 337, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-338', 'SETUP', 'Настройка датчиков (LPC, Cut-off, склейка и др.)', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 338, 'POUCH', 'Packaging', 'Указать датчик, причину, местоположение', 'Ts'),
    ('POUCH-339', 'SETUP', 'Настройка сварных панелей', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 339, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('POUCH-340', 'SETUP', 'Настройка тянущих валов', True, True, True, 'AVAILABILITY', 'PLANNED_STOP', 340, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Ts'),
    ('POUCH-341', 'DOWNTIME', 'Установка/снятие рулона с полуфабрикатом в машину', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 341, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-342', 'DOWNTIME', 'Обрыв трима', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 342, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-343', 'DOWNTIME', 'Замена сварных элементов (нагревателей)', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 343, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-344', 'DOWNTIME', 'Чистка вакуумной системы удаления отходов', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 344, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
    ('POUCH-345', 'DOWNTIME', 'Start-up', False, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 345, 'POUCH', 'Packaging', 'Указать причину', 'Td'),
    ('POUCH-346', 'DOWNTIME', 'Срабатывание защитной системы', True, True, True, 'AVAILABILITY', 'UNPLANNED_STOP', 346, 'POUCH', 'Packaging', 'Указать причину, местоположение', 'Td'),
]

# Zero Pull setup tags (reasons for repeated setup attempts at code OGP-120)
# (tag, name, description, sort_order)
SETUP_TAGS = [
    ('Zerropull', '0 — Zerropull', 'Первый заезд настройки / плановая проверка Zero Pull', 0),
    ('A', 'A', 'В ходе проверки качества печати, параметры не в спецификации - грамматура, ширина печати, размер этикетки и т.д.', 1),
    ('B', 'B', 'Вязкость не соответсвует заданной, на оттиске видны дефекты- "рыбий глаз", "выливание" и тд', 2),
    ('C', 'C', 'Оптическая плотность CMYK не в спецификации или элемент печати, в наложении, визаульно имеет отклонения от стандарта', 3),
    ('D', 'D', '∆Eсмс,∆E2000,Lab - вне целевых спецификаций', 4),
    ('E', 'E', 'При визуальной оценке видно расхождение с графическим стандартом', 5),
    ('F', 'F', 'Остановка из-за загрязнений в краске и сопровождающих дефектов, например негативов', 6),
    ('G', 'G', 'Вынужденная остановка связана с техническим состоянием машины, например - не дожимает прессёр с одной стороны, медленно вращающийся вал срывает краску, конденсат на валах и тд', 7),
    ('H', 'H', 'Вынужденная остановка из-за проблем с приводкой цветов, лаков и клеев', 8),
    ('I', 'I', 'На полученном оттиске обнаружен дефект цилиндра', 9),
    ('J', 'J', 'Некачественная сборка ракеля привела к дефектам на старте', 10),
    ('K', 'K', 'Засыхание ЛКМ на цилиндре, цилиндр не очищен, непропечатки, грамматура ниже целевой', 11),
    ('L', 'L', 'Дефекты печати не подподающие по стандаотное описание. Более подробная информация должна быть описана в комментарии к коду', 12),
    ('M', 'M', 'Проблемы вызванные сырьевым печатным материалам. Более подробная информация должна быть описана в комментарии к коду', 13),
    ('N', 'N', 'Более подробная информация должна быть описана в комментарии к коду', 14),
    ('P', 'P', 'В ходе проверки качества печати, визуального или приборного отклонения не обнаружено', 16),
]
